### ISSUE TITLE
DEBUG multiple categories using regexp (BZ#1062)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1062]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#1062
From: Tripun (@tripun)
CC:   @tripun

**Comment by daraul** [comment]
I knew I did this before, but couldn't find it mentioned in the docs, so I added an MR for that at #1956.

**Comment by tbm** [comment]
@daraul my apologies for the *huge* delay. Life got in the way... I've applied your patch now. Thank you!
