### ISSUE TITLE
"bucket" does not work when there are multiple postings for a transaction (BZ#1131)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1131]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#1131
From: Daniel Patterson (@danpat)

**Comment by shentino** [comment]
Same issue here.

Offending journal:

bucket Assets:Cash

2019/02/10 * Jane Doe
  Revenue:Labor:Lawnmowing   $-40.00
  Expenses:Tithe               $4.00
  Liabilities:Tithe           $-4.00

**Comment by tbm** [comment]
This is not how `bucket` works.  The `bucket` directive allows you to have *one* posting and the second posting fill by filled with the bucket.

You can't use this to fill in a third or fourth posting.  How would ledger know it should use bucket vs when you make an error?  If this were to work, it would be a good way to introduce problems that are hard to track down.  The whole point is that a transaction needs to *balance*.  This avoids errors.

(In my personal view, `bucket` shouldn't exist at all due to these reasons, but at least since it only works with transactions with one single posting it limits potential errors a bit.)

@danpat, @shentino: this is not a bug. Please specify all postings explicitly.
