### ISSUE TITLE
please provide python3 bindings (BZ#1203)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1203]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#1203
From: David Bremner (@bremner)

**Comment by simevo** [comment]
Please release this fix, we need it to make python3-ledger package in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857335
Thanks !

**Comment by jwiegley** [comment]
@tbm Can we cut a release from current `master`?

**Comment by tbm** [comment]
@jwiegley there are still a number of Python3 related test failures.  Although I suppose what we have now is better than the current official release.

@xnox do you have time to look into the remaining test failures?
