### ISSUE TITLE
ledger budget with commodity conversion (-X) errors (BZ#1223)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1223]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#1223
From: unknown reporter

**Comment by tbm** [comment]
The same as just reported as #1694. I'll close this bug since the other one has more info

**Comment by Zimmi48** [comment]
@tbm You said you were closing but apparently forgot to do it.

**Comment by tbm** [comment]
Duplicate of #1694.
