### ISSUE TITLE
Building on Arch Linux (BZ#456)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1528]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#456
From: John Wiegley (@jwiegley)

**Comment by escondida** [comment]
This one we can probably go ahead and close: there's an official package in the Arch repos, and I can verify that it builds just fine on Arch just by following the documentation.

**Comment by jwiegley** [comment]
Thanks!
