### ISSUE TITLE
Add --time-colon option (BZ#496)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1568]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#496
From: John Wiegley (@jwiegley)
CC:   @afh

**Comment by rafasc** [comment]
This should be closed.

**Comment by tbm** [comment]
commit 36f87f49d86e931bb99a226cd47721219ccd6301
Author: Alexis Hildebrandt <afh@surryhill.net>
Date:   Mon Sep 6 15:01:09 2010 +0200

    Add --time-colon option
