### ISSUE TITLE
The documentation uses average on balance which I'm told doesn't work

### ISSUE THREAD

**Issue by ndw** [ledger/ledger#1646]
In this thread:

https://groups.google.com/forum/#!topic/ledger-cli/Xqn2sDLhMhE

I asked about using --monthly --average on balances, using an example taken directly from the docs:

https://www.ledger-cli.org/3.0/doc/ledger3.html#Budgeting-and-Forecasting

A follow up to my post suggests that monthly average on balances simply doesn't work. If that's the case, and it's certainly consistent with my experience, the docs need to be fixed.

**Comment by oguzserbetci** [comment]
This made me scratch my head a lot today. I think this would be such a nice to have as it is very important to know how much one spends on each category on average.

```
2019/01/01 Rent
    Expenses:Rent  200EUR
    Assets

2019/01/02 Rent
    Expenses:Rent  200EUR
    Assets

2019/02/01 Rent
    Expenses:Rent  400EUR
    Assets
```

Running `ledger -MA balance expenses` should generate 400EUR per month, but it calculates 160EUR. Correct behaviour would be to first group by month, sum up the groups and then take the average.

Please correct me if the current calculation actually has a logical explanation. I would also be happy to contribute if you can point me to where this all happens :)
