### ISSUE TITLE
Undetected error when mixing currencies

### ISSUE THREAD

**Issue by DamienCassou** [ledger/ledger#1648]
```ledger
2018-06-08 * Opening Balance
    Assets:Checking:EUR                            1€
    Assets:Checking:SEK                            2SEK
    Equity:Opening Balances                       -100000€
    Equity:Opening Balances                       -1000€
```

This is recognized as a valid transaction even though it looks incorrect to me (I'm completely new to ledger so it's most probably me who is incorrect). There is nothing else in the file.

```session
$ ledger -f bug.ledger balance
                2SEK
                  1€  Assets:Checking
                  1€    EUR
                2SEK    SEK
            -101000€  Equity:Opening Balances
--------------------
                2SEK
            -100999€
```

I'm using ledger package from Fedora: 3.1.1-20160111

**Comment by tbm** [comment]
When there are 2 commodities, ledger does an implicit conversion.  Therefore, it believes that 100999 EUR equals 2 SEK.

$ ledger -f d pricedb
P 2018/06/08 00:00:00 € 0.000019802176SEK

**Comment by DamienCassou** [comment]
This makes sense, sorry for the noise.

**Comment by tbm** [comment]
Note that I personally don't like this behaviour (as it leads to issues like the one you describe), but it is ledger's behaviour and some people like the implicit conversion.
