### ISSUE TITLE
ledger csv strips out transactions with zero amount

### ISSUE THREAD

**Issue by trevorld** [ledger/ledger#1652]
Sorry if this is a duplicate but I couldn't find it in the issues.   I'm observing that ``ledger csv`` strips out items with a zero amount from its output:

```
$ cat test.ledger
account Assets:A
account Assets:B
account Income:Wages

2018-01-01 * Example with no zero amount
    Assets:A    40 USD
    Assets:B    20 USD
    Income:Wages

2018-01-02 * Example with zero amount
    Assets:A    40 USD
    Assets:B     0 USD
    Income:Wages
$ ledger csv -f test.ledger 
"2018/01/01","","Example with no zero amount","Assets:A","USD","40","*",""
"2018/01/01","","Example with no zero amount","Assets:B","USD","20","*",""
"2018/01/01","","Example with no zero amount","Income:Wages","USD","-60","*",""
"2018/01/02","","Example with zero amount","Assets:A","USD","40","*",""
"2018/01/02","","Example with zero amount","Income:Wages","USD","-40","*",""
```

In comparison ``beancount`` and ``hledger`` both output items with zero amount although hledger currently doesn't assign a commodity to them:

```
$ hledger register -f test.ledger -o test.csv; cat test.csv
"txnidx","date","description","account","amount","total"
"1","2018/01/01","Example with no zero amount","Assets:A","40 USD","40 USD"
"1","2018/01/01","Example with no zero amount","Assets:B","20 USD","60 USD"
"1","2018/01/01","Example with no zero amount","Income:Wages","-60 USD","0"
"2","2018/01/02","Example with zero amount","Assets:A","40 USD","40 USD"
"2","2018/01/02","Example with zero amount","Assets:B","0","40 USD"
"2","2018/01/02","Example with zero amount","Income:Wages","-40 USD","0"
$ bean-query -f csv test.beancount "SELECT *"
date,flag,payee,narration,position
2018-01-01,*,,Example with no zero amount, 40 USD
2018-01-01,*,,Example with no zero amount, 20 USD
2018-01-01,*,,Example with no zero amount,-60 USD
2018-01-02,*,,Example with zero amount   , 40 USD
2018-01-02,*,,Example with zero amount   ,  0 USD
2018-01-02,*,,Example with zero amount   ,-40 USD
```

**Comment by tbm** [comment]
Can you explain why/when you'd have 0?

**Comment by trevorld** [comment]
The example beancount file has zeros (my personal ledger doesn't).  I venture a guess that in the example he is using the zeroes to explicitly track that zero 401K employee contributions were made for that paycheck (because the 18K yearly limit had been hit).  As a bonus this also ensures every paycheck transaction all have the same type of lines (easy to verify nothing has been missed when recording information from the paystub and allows a user to copy and paste a common transaction like paycheck and simply zero out certain lines that were zero that period (like 401K contributions once the 18K a year max had been hit).  

Also, if one did not strip such zeroes in the csv export then one could for example import the csv into a program like R and then make a time series chart of 401k employee contributions by pay period and it would accurately show zero data points for those pay periods.  The value of keeping the zeroes in the csv export would be primarily for further such fine-tuned data analysis and data plotting - they obviously have no impact on computing a balance / net worth / income statement. 

If a user wants to explicitly track a zero is there a good reason to discard them (other than to achieve a minuscule performance gain)?

**Comment by trevorld** [comment]
Besides plotting certain time series another theoretical value in keeping the zeroes in the csv output would be to allow regression analysis of various transactions (i.e. panel data analysis with time fixed effects).  Stripping zero transactions could introduce data problems (i.e. besides "missing" data the data would no longer be "balanced") in such analysis.

**Comment by tbm** [comment]
I think this works as expected.

It works the way you want when you add `--empty`.

**Comment by trevorld** [comment]
Adding the ``--empty`` flag seems to do the trick.  Thanks for the follow-up, sorry I missed that detail in the documentation.
