### ISSUE TITLE
ledger doesn't learn commodity format from balance assertions

### ISSUE THREAD

**Issue by kcwu** [ledger/ledger#1654]
```
2018/01/01 foo
        Account  = 10 USD
        Equity
```
The result of `ledger balance` is
```
               USD10  Account
              USD-10  Equity
--------------------
                   0
```
However, I expect they should be
```
              10 USD  Account
             -10 USD  Equity
--------------------
                   0
```

**Comment by jwiegley** [comment]
I think we just aren't "observing" characteristics in account balancing amounts.

You can always put this at the top of your file:

```
D 1.00 USD
```

**Comment by jwiegley** [comment]
@tbm I'm not sure we *want* to observe characteristics here, either. For example, we don't for costs either, to allow the user to be more precise in those places without blowing up the precision used on output. What do you think?

**Comment by tbm** [comment]
> For example, we don't for costs either, to allow the user to be more precise in those places without blowing up the precision used on output. What do you think?

I'd say a balance assertion is different to a cost because a balance assertion should always have the same precision as regular transactions.  Am I missing something?

**Comment by jwiegley** [comment]
That makes sense to me too.
