### ISSUE TITLE
parsing problem for dates on cli for xact in MacOS High Sierra

### ISSUE THREAD

**Issue by cacology** [ledger/ledger#1661]
Calling ledger xact on the command line throws an error when given a date in MacOS High Sierra.

My `uname -v` is `Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64`

temp.ledger:
```ledger
2018/07/15 Reoccuring
    Assets:Savings                            $75.00
    Assets:Checking                          -$75.00
```

`ledger -f temp.ledger xact 2018/08/15 Reoccuring` gives `Error: Invalid date:`

`ledger -f temp.ledger template 2018/08/15 Reoccuring` gives:
```
Error: Invalid date:
--- Input arguments ---
("2018/08/15", "Reoccuring")
```

But

`ledger -f temp.ledger template Reoccuring` gives:
```
--- Input arguments ---
("Reoccuring")

--- Transaction template ---
Date:       <today>
Payee mask: Reoccuring

<Posting copied from last related transaction>
```

I'm not able to compile using Homebrew to get the debugging symbols, but I wonder if anyone else can reproduce this bug.

Respectfully submitted,
-James

**Comment by tbm** [comment]
This might be the same as issue #546 which got fixed recently.

Does Homebrew build from the 'next' branch or does it use the latest release?

**Comment by cacology** [comment]
You're right, issue #546 fixes it.  I confirmed by building from the 'next' branch and running that one.  You're also right the homebrew formula uses the current release, which I think is on purpose.

I'm not involved enough with homebrew development to know how they'd like to have the next/alpha branch in their formula, or with ledger development to know whether or not your bug fix should be applied to the current stable.

**Comment by tbm** [comment]
A new stable release is longer overdue.  See issue #523.

I'll close this bug as a duplicate.
