### ISSUE TITLE
An icon for ledger files?

### ISSUE THREAD

**Issue by Alexander-Miller** [ledger/ledger#1669]
Hello there,

since I am beginning to make more and more use of ledger I would like to properly integrate it with [treemacs](https://github.com/Alexander-Miller/treemacs) by giving .ledger files a proper icon. I lack the skill to make something myself and haven't found anything fitting on google, so I'm left with asking around.

The potential icon just needs to look reasonably nice as a 22x22 px png image on both dark and bright backgrounds. Beyond that there are no requirements.

**Comment by escondida** [comment]
I'm not much for iconography myself, but I've attached a bare-bones suggestion. I will not be insulted if someone suggests something better (-:

Rationale:
- scales: everything must balance
- generic currency symbols in scales: ledger doesn't care what unit, if any, you use
- simply 3 Unicode characters composed together: ledger is all about plain text.

If y'all like it, I donate it unreservedly to the cause.

Correction: github despises me and will not let me attach files. Instead, find them at the following locations:

[Original gimpfile: 128x128px](https://escondida.tk/images/ledger/ledger_icon.xcf)
[Exported png](https://escondida.tk/images/ledger/ledger_icon.png)
[16x16 png to show how it compresses (not bad; not good, though)](https://escondida.tk/images/ledger/ledger_icon_16x16.png)

**Comment by Alexander-Miller** [comment]
It looks nice enough I think: https://imgur.com/a/xQDuzn7. You cannot really see the details of what's in the scales, but that's negligible. 

Unfortunately the color is a real issue. Black is a no-go when your default background is #2d2d31. A static background color like in my [js icon](https://github.com/Alexander-Miller/treemacs/blob/master/icons/js.png) should do the trick.

I'll see what I can do, but help would be much appreciated - I'm not that great at picking colors either.

**Comment by Alexander-Miller** [comment]
Did some recoloring, [I think it looks ok now.](https://imgur.com/a/47WusLI)
