### ISSUE TITLE
export PAGER makes ledger not to use pager

### ISSUE THREAD

**Issue by devmsv** [ledger/ledger#1674]
Title say it all. I am using OpenBSD -current

* OS:        OpenBSD 6.3 GENERIC.MP#180 amd64
* (ledger version:       Ledger 3.1.1-20160111

specifying --force-pager doesn't fix the issue  but --pager "less -R" does it.

**Comment by larryhynes** [comment]
What happens if you put `--pager less` in `~/.ledgerrc`?

**Comment by devmsv** [comment]
Then it works

**Comment by tbm** [comment]
Confirmed
