### ISSUE TITLE
bash completion script not working with all bash versions?

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1683]
```
tbm@jirafa: bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
tbm@jirafa: source contrib/ledger-completion.bash 
bash: contrib/ledger-completion.bash: line 62: syntax error near unexpected token `('
bash: contrib/ledger-completion.bash: line 62: `        --@(cache|file|init-file|output|pager|price-db|script)|-@(f|i|o))'
tbm@jirafa: 
```

@bruno-

**Comment by tbm** [comment]
@bruno- can you look at this?

**Comment by bruno-** [comment]
First update:

I have quick access to systems with 2 bash versions `4.4.23(1)` on mac os and `4.3.11(1)` on ubuntu 14.04. Both systems have `ledger` installed the standard way (`apt-get` and `brew`) and I was unable to reproduce.

Here's what I did on both systems:
```bash
curl https://raw.githubusercontent.com/ledger/ledger/next/contrib/ledger-completion.bash > file.bash
source file.bash
```

There were no errors and the exit status was 0 (success).

I'll continue investigating.

**Comment by bruno-** [comment]
Additionally I tested this on Linux ubuntus with bash versions: `4.3.48` and `4.4.19`. I couldn't reproduce this issue on either version.

I'll try installing bash `4.4.11` and seeing how it behaves.

**Comment by tbm** [comment]
Hmm, this is very weird.  I just tried on another Debian system and I cannot reproduce the issue there (same version of bash).  I do see it on my laptop though.

Anyway, since you cannot reproduce it and I only see it on my laptop, let's just close this ticket.  Sorry for the noise.

**Comment by gmenzel** [comment]
In case it's of any interest, I just ran across this same problem on macOS, and it was caused by not having the bash-completion2 package installed.
