### ISSUE TITLE
document: balance assignments work in parse order not in date order

### ISSUE THREAD

**Issue by helguson** [ledger/ledger#1687]
The documentation on [balance assigments](https://www.ledger-cli.org/3.0/doc/ledger3.html#Resetting-a-balance) states that you can use this feature for setting a balance to a specified value. Yet the documentation does not mention that it works in parse order and not in date order. This leads to some confusion as for some users date order is more intuitive, e.g.,  #1092, #111, or myself.
For this reason I suggest to add this fact to the documentation.

**Comment by tbm** [comment]
@helguson can you submit a patch for this?

**Comment by tbm** [comment]
@helguson can you submit a patch for this?

**Comment by afh** [comment]
I've put up #2184 to address this. @helguson what are your thoughts on the wording? Does the changes in the PR explain the "limitations" of balance assertions and assignments well?

**Comment by afh** [comment]
Closing as #2184 has been merged.

@helguson do provide feedback or another PR if you believe the wording introduced with #2184 could be improved.
