### ISSUE TITLE
Worg in documentation needs link

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1690]
The docs say:

> As of Org mode 7.01, Ledger support is provided.  Check the Babel
> documentation on Worg for instructions on how to achieve this but

This should be a link. Is this the right link @jwiegley: https://orgmode.org/worg/org-contrib/babel/

**Comment by tbm** [comment]
@jwiegley can you comment

**Comment by jwiegley** [comment]
That looks right to me!
