### ISSUE TITLE
Smaller footprint

### ISSUE THREAD

**Issue by emKaroly** [ledger/ledger#1697]
I am using ledger on MacOS installed with homebrew and i noticed that it installs a lot of dependencies boost(514MB) boost-python(20MB) python2(100MB)
Are there any plans to move to Python3 so we don't have to install legacy Python and shrink the boost package to only necessary stuff(i found that boost provide tool to extract only necessary stuff from the whole library: https://www.boost.org/doc/libs/1_53_0/tools/bcp/doc/html/index.html)

**Comment by ngleb** [comment]
You can track progress of Python 3 port here: https://github.com/ledger/ledger/issues/510

ledger doesn't contain boost library, it's up to the distribution (i.e. homebrew in your case) to properly split the package. probably someone could make a static package with only necessary stuff, but ledger doesn't offer binaries.

**Comment by emKaroly** [comment]
Ok so the homebrew team doesn't really want to answer my question about splitting the boost package i believe its and excess work they don't want to do. So if you migrate to python 3 its all you can do in that case. So i am closing the issue, thank you for your time.
