### ISSUE TITLE
baseline/cmd-org.test fails

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1706]
I see:

```
/usr/bin/python2.7 "/home/tbm/ledger/test/RegressTests.py" "/home/tbm/ledger/ledger" "/home/tbm/ledger" "/home/tbm/ledger/test/baseline/cmd-org.test"

FAILURE in output from /home/tbm/ledger/test/baseline/cmd-org.test:
--
$ledger -f "/home/tbm/ledger/test/baseline/cmd-org.test" org
--
  @@ -5,8 +5,6 @@
   |||Test 3|*|D|-20.00 EUR|0.00 EUR| Payee: Test 3
   |12-Mar-25|99|Test 4|*|E|30.00 GBP|30.00 GBP|
   ||||*|F|-30.00 GBP|0.00 GBP|
  -|12-Mar-26|test|Test 5|*|G|1 AAA|0.00 GBP|
  -|||||||1 AAA|
  -||||*|H|$-10|0.00 GBP|
  +|12-Mar-26|test|Test 5|*|G|1 AAA|1 AAA|
  +||||*|H|$-10|1 AAA|
   |||||||$-10|
  -|||||||1 AAA|
E[cmd-org.test]STDERR:
```

**Comment by tbm** [comment]
Smaller test case:

```
2012-03-26 * Test 5
    G          1 AAA @ $10.00
    H
```

normal ledger output:

```
|Date|Code|Payee|X|Account|Amount|Total|Note|
|-|
|||<20>|||<r>|<r>|<20>|
|2012-03-26||Test 5|*|G|1 AAA|1 AAA|
||||*|H|$-10|$-10|
|||||||1 AAA|
```

ledger on Debian unstable:

```
|Date|Code|Payee|X|Account|Amount|Total|Note|
|-|
|||<20>|||<r>|<r>|<20>|
|12-Mar-26||Test 5|*|G|1 AAA|1 AAA|
||||*|H|$-10|1 AAA|
|||||||$-10|
```

**Comment by scfc** [comment]
To correct myself: The actual output is:

    FAILURE in output from /src/ledger/test/baseline/cmd-org.test:
    --
    $ledger -f "/src/ledger/test/baseline/cmd-org.test" org
    --
      @@ -5,8 +5,6 @@
       |||Test 3|*|D|-20.00 EUR|0.00 EUR| Payee: Test 3
       |12-Mar-25|99|Test 4|*|E|30.00 GBP|30.00 GBP|
       ||||*|F|-30.00 GBP|0.00 GBP|
      -|12-Mar-26|test|Test 5|*|G|1 AAA|0.00 GBP|
      -|||||||1 AAA|
      -||||*|H|$-10|0.00 GBP|
      +|12-Mar-26|test|Test 5|*|G|1 AAA|1 AAA|
      +||||*|H|$-10|1 AAA|
       |||||||$-10|
      -|||||||1 AAA|
    E[cmd-org.test]STDERR:
    FAILED (1)

I believe this is the same issue, but I have not confirmed it.

**Comment by tbm** [comment]
@tko since you tracked down the garbled date issue (#546), do you think you could take a look at this issue? ;)

No good deed goes unpunished right.

**Comment by tko** [comment]
@tbm I can't reproduce that on macos and I don't have linux readily available, so not very quickly.

If this is similar memory corruption issue running ledger in valgrind might help point to right direction.

(I did get test failure on `BaselineTest_opt-lots` though but haven't looked at it either.)

**Comment by scfc** [comment]
The issue also appears on `master` when compiled on Fedora 28.  I thought that maybe that is related to Fedora's boost 1.66 vs. Travis CI's 1.61, but bumping `BOOST_VERSION_MAX` to `1.66.0` in `.travis.yml` did not trigger the error (https://travis-ci.org/scfc/ledger/jobs/480875026).

**Comment by scfc** [comment]
The issue remains with `master` on Fedora 28 with Boost 1.61, so maybe the difference in `gcc` (4.8.4 vs. 8.2.1) triggers a bug.

**Comment by tko** [comment]
Seems that running ledger in valgrind makes it behave correctly...

With `--debug 'expr|format'` logging I see some differences between runs. Everything is about identical until we get to
```
 <ms>  [DEBUG] Calculating: (scrub(top_amount(display_total)))
 <ms>  [DEBUG]   scrub(top_amount(display_total)) => ...
 <ms>  [DEBUG] .  top_amount(display_total) => ...
 <ms>  [DEBUG] ..  display_total => ...
 <ms>  [DEBUG] ...  <FUNCTION> => ...
 <ms>  [DEBUG] Calculating: total_expr
 <ms>  [DEBUG]   total_expr => ...
 <ms>  [DEBUG] .  <FUNCTION> => ...
 <ms>  [DEBUG] Calculating: total
 <ms>  [DEBUG]   total => ...
 <ms>  [DEBUG] .  <FUNCTION> => ...
 <ms>  [DEBUG] .  <FUNCTION> => $-10
 1 AAA {$10} [12-Mar-26]
 <ms>  [DEBUG]   total => $-10
 1 AAA {$10} [12-Mar-26]
 <ms>  [DEBUG] .  <FUNCTION> => $-10
 1 AAA {$10} [12-Mar-26]
 <ms>  [DEBUG]   total_expr => $-10
 1 AAA {$10} [12-Mar-26]
 <ms>  [DEBUG] ...  <FUNCTION> => $-10
 1 AAA {$10} [12-Mar-26]
 <ms>  [DEBUG] ..  display_total => $-10
 1 AAA {$10} [12-Mar-26]
```

Next, when it's working:
```
 <ms>  [DEBUG] .  top_amount(display_total) => $-10
 <ms>  [DEBUG]   scrub(top_amount(display_total)) => $-10
 <ms>  [DEBUG] value = ($-10)
```

Or when broken:
```
 <ms>  [DEBUG] .  top_amount(display_total) => 1 AAA {$10} [12-Mar-26]
 <ms>  [DEBUG]   scrub(top_amount(display_total)) => 1 AAA
 <ms>  [DEBUG] value = (1 AAA)
```

I've no idea what to do with this information.

That running in valgrind changes things slightly suggests something related to timing perhaps. Maybe there's some sub-microsecond timer (in)equality that gets disturbed causing things to get reordered.

**Comment by scfc** [comment]
For completeness: Travis CI succeeds with `gcc` at 5.4.0, 6.5.0, 7.4.0 and 8.1.0.  Fedora 28 uses `gcc` 8.2.1.

**Comment by scfc** [comment]
Uh, sorry.  On Ubuntu Cosmic, the output (as part of `make check`) is:

    226/372 Test #228: RegressTest_1057 ......................................***Failed    2.75 sec
    FAILURE in output from /ledger/test/regress/1057.test:
    --
    $ledger -f "/ledger/test/regress/1057.test" --now=2014/06/27 emacs
    --
      @@ -1,4 +1,4 @@
      -(("/ledger/test/regress/1057.test" 1 (21308 60112 0) nil "www.amazon.fr"
      +(("/ledger/test/regress/1057.test" 1 (21308 42112 0) nil "www.amazon.fr"
         (2 "Dépense:Loisir:Ordi:Matériel" "101,50 €" nil " disque dur portable 2,5\" 2000 Go")
         (3 "Dépense:Maison:Service:Poste" "70,13 €" nil)
         (4 "Passif:Crédit:BanqueAccord" "-171,63 €" t)))
    E[1057.test]STDERR:
    FAILED (1)

Running it manually does not change the `42112`:

    root@101dcd18cf57:/ledger# python ./test/RegressTests.py ./ledger ./ test/regress/1057.test
    
    FAILURE in output from test/regress/1057.test:
    --
    $ledger -f "/ledger/test/regress/1057.test" --now=2014/06/27 emacs
    --
      @@ -1,4 +1,4 @@
      -(("/ledger/test/regress/1057.test" 1 (21308 60112 0) nil "www.amazon.fr"
      +(("/ledger/test/regress/1057.test" 1 (21308 42112 0) nil "www.amazon.fr"
         (2 "Dépense:Loisir:Ordi:Matériel" "101,50 €" nil " disque dur portable 2,5\" 2000 Go")
         (3 "Dépense:Maison:Service:Poste" "70,13 €" nil)
         (4 "Passif:Crédit:BanqueAccord" "-171,63 €" t)))
    E[1057.test]STDERR:
    
    
    FAILED (1)
    root@101dcd18cf57:/ledger#

**Comment by tbm** [comment]
Let's continue to discuss the RegressTest_1057 failure in issue #1739 and let's keep this ticket for the other issue.

**Comment by tbm** [comment]
@tko can you look at the BaselineTest_opt-lots issue you mention and open a new issue if it's a real bug.

**Comment by jwiegley** [comment]
Those are Emacs Lisp date/time values.

**Comment by jwiegley** [comment]
I was able to reproduce the Docker results here, but no ideas as of yet.

**Comment by tbm** [comment]
@mbudde any chance you can take a look?

**Comment by mbudde** [comment]
`amounts_map` in `balance_t` is defined like this:
https://github.com/ledger/ledger/blob/0c0f696fd2ae0e3d801bb0b534f9f20bcacc86b2/src/balance.h#L83
The code in `org.cc` iterates over this map. Since the keys in the map are pointers the order of the items [depends on the pointer values](https://stackoverflow.com/questions/25122932/pointers-as-keys-in-map-c-stl). Something has changed (in GCC perhaps) that has caused the commodity pointers to have a different ordering in Cosmic, thus changing the output.

I'm not sure how to fix it though. I guess `org.cc` should be modified in some way such that the amounts always are iterated in a deterministic order.

**Comment by jwiegley** [comment]
Ahh, that makes sense! thanks `mbudde`.

In `org.cc`, we could project this map into a map of the following type:

    std::map<std::pair<std::string, commodity_t *>, amount_t>

I.e., just turn every key into a pairing of its commodity name and the pointer.

Then `org.cc` would iterate this map and ignore the commodity name part. Should be a few-liner.

**Comment by tbm** [comment]
@jwiegley removed the `org` command in f0dacdb22f2888 so I'm closing this issue.

**Comment by tbm** [comment]
@jwiegley removed the org command in f0dacdb so I'm closing this issue.
