### ISSUE TITLE
Set up Travis CI for Windows

### ISSUE THREAD

**Issue by scfc** [ledger/ledger#1709]
Travis CI [now supports](https://docs.travis-ci.com/user/reference/windows/) "Windows Server, version 1803".

@AlexanderAA, @orlandow, as you compiled the Ledger binaries for Windows in the past, can you comment on whether that is a useful environment to test whether Ledger would compile "on Windows"?

**Comment by orlandow** [comment]
I guess it should work, I think it's the same process once you install cygwin regardless of it being a Windows server or a regular Windows. I'm not sure about what OS dependencies are required though; when I compiled it, I hadn't used cygwin before, I just followed some tutorial and got it working. Sorry if I can't be more helpful.

**Comment by tbm** [comment]
Can someone contribute a Travis config?

**Comment by jwiegley** [comment]
Or what if we move to GitHub Actions?

**Comment by tbm** [comment]
@orlandow @scfc @kunedo is one of you interested in working on this?

**Comment by afh** [comment]
Closing as Travis is no longer used.
