### ISSUE TITLE
RegressTest_1057 fails

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1739]
@scfc reported that RegressTest_1057 fails on Ubuntu Cosmic.

On Debian stable, 'make check' works but when I run the test manually using:

    python ./test/RegressTests.py ./ledger ./ test/regress/1057.test

I also get a failure:
```
  -(("/home/tbm/tmp/src/ledger/test/regress/1057.test" 1 (21308 60112 0) nil "www.amazon.fr"
  +(("/home/tbm/tmp/src/ledger/test/regress/1057.test" 1 (21308 52912 0) nil "www.amazon.fr"
```

**Comment by mbudde** [comment]
The test depends on the timezone, so if you run it manually you need to set TZ:
```
TZ=America/Chicago python ./test/RegressTests.py ./ledger ./ test/regress/1057.test
```

**Comment by tbm** [comment]
Good point @mbudde. I don't get a failure now. @scfc?

**Comment by mbudde** [comment]
That @scfc got the same result from running the test manually and via `make check` makes me suspect that for some reason the timezone does not get set properly in Ubuntu Cosmic. Setting `TZ=Europe/Hamburg` (which I believe is @scfc's timezone) I get the exact same failure:
```
  -(("/home/michael/Code/cloned/ledger/test/regress/1057.test" 1 (21308 60112 0) nil "www.amazon.fr"
  +(("/home/michael/Code/cloned/ledger/test/regress/1057.test" 1 (21308 42112 0) nil "www.amazon.fr"
```

**Comment by scfc** [comment]
No, my time zone is UTC :-) (but `Europe/Hamburg` is equal to that as it does not exist).  But the problem appears to be that at least in the Ubuntu Cosmic _Docker_ images the time zone database is no longer included and thus symbolic names like `America/Chicago` no longer recognized:

    [tim@passepartout ~/src/ledger]$ (for release in trusty cosmic; do echo -n "$release: "; sudo docker run -e TZ=America/Chicago "ubuntu:$release" date; done)
    trusty: Tue Jan 22 13:48:46 CST 2019
    cosmic: Tue Jan 22 19:48:47 America 2019
    [tim@passepartout ~/src/ledger]$

This can be solved by installing the package `tzdata` after which this issue disappears.

Also, this could be worked around by specifying the time zone data directly:

    [tim@passepartout ~/src/ledger]$ TZ=America/Chicago date; (for release in trusty cosmic; do echo -n "$release: "; sudo docker run -e TZ=CST+6 "ubuntu:$release" date; done)
    Di 22. Jan 13:54:31 CST 2019
    trusty: Tue Jan 22 13:54:32 CST 2019
    cosmic: Tue Jan 22 13:54:33 CST 2019
    [tim@passepartout ~/src/ledger]$

However this would probably open up a can of worms.  I think adding `tzdata` to the list of build dependencies (in `acprep` & Co.) is probably preferable.  For most systems, this would be a noop anyway.
