### ISSUE TITLE
file with unknown license contrib/CSVReader.cs

### ISSUE THREAD

**Issue by bremner** [ledger/ledger#1758]
Quoting from the file

```
// This code is in the public domain.  I can't remember where I found it on the Web, but it
// didn't come with any license.
```

I'm not a lawyer, but I don't think that's how public domain works ;)

**Comment by jwiegley** [comment]
Right you are, @bremner! I've sent a message to the author, J.Marc Piulachs, asking if he will clarify the licensin

**Comment by tbm** [comment]
> Right you are, @bremner! I've sent a message to the author, J.Marc Piulachs, asking if he will clarify the licensing.

@jwiegley  did you hear back from him?

**Comment by jwiegley** [comment]
I don't recall that I did.

**Comment by tbm** [comment]
@jwiegley any objections to removing the following files to do the missing license in contrib/CSVReader.cs?

```
contrib/CSVReader.cs
contrib/Makefile
contrib/ParseCcStmt.cs
```

**Comment by jwiegley** [comment]
I'm fine with that.
