### ISSUE TITLE
Minfied JS without source in python/res

### ISSUE THREAD

**Issue by bremner** [ledger/ledger#1759]
There are several minified JS files in python/res without the corresponding (non-minified) source. This means they need to be stripped from the package by Debian and probably by other Distros as well.

**Comment by jwiegley** [comment]
Good catch. I wonder which version of jQuery that is...

**Comment by tbm** [comment]
It would be nice to fix this before a new release.

I thought there was some discussion about this issue but I don't see it.  @bremner do you know where the code is from? Can you submit a PR?

**Comment by tbm** [comment]
@bremner do you know where the code is from? Can you submit a PR?

**Comment by tbm** [comment]
just seems to be jquery

**Comment by tbm** [comment]
The only script that depends on the jquery in python/res is python/server.py, which doesn't seem to actually work:

```
  File "server.py", line 111, in __init__
    self.journal = ledger.Journal(sys.argv[1])
ArgumentError: Python argument types in
    Journal.__init__(Journal, str)
did not match C++ signature:
    __init__(_object*)
```

@jwiegley do you know the fix?  Is python/server.py worth keeping?  If we remove it, we could remove the jquery from python/res, which would fix this license issue.

Of course, we could just embed all of jquery... but is it worth it? (Or remove the jquery dependency from server.py).

**Comment by jwiegley** [comment]
It's not worth it to me, I don't even know who's using it. Feel free to drop it.

**Comment by tbm** [comment]
Thanks for your comment @jwiegley!

**Comment by tbm** [comment]
... and for being as accommodating as always :)
