### ISSUE TITLE
Sort by auxiliary date 

### ISSUE THREAD

**Issue by fancsali** [ledger/ledger#1772]
I keep my journals separate by source (as in which bank statement they come from), and then merge them for final processing..

However, when merging them together, it'd be nice to have a way of sorting them based on the aux_date, if present, and date if the former is not specified. However if I do `cat *.ldg | ledger print -f - --effective --sort date --permissive  --detail > all.ldg` I essentially lose the two dates.

What I am trying to achieve is sorting by one date, but keeping both of them. I believe, this functionalityis not present at the moment. Might be worth thinking about adding it.

**Comment by tbm** [comment]
It sounds like the real bug here is that `print --effective` does not retain the whole date information.

```
65559:tbm@jirafa: ~/src/ledger] ledger -f d print            
2014-04-03=2012-03-26 * Test 5
    G                                          1 AAA @ $10
    H
65560:tbm@jirafa: ~/src/ledger] ledger -f d print --effective
2012-03-26 * Test 5
    G                                          1 AAA @ $10
    H
```

**Comment by tbm** [comment]
`--effective --raw --sort d` works for me

**Comment by fancsali** [comment]
`--raw` seems to do the trick...
