### ISSUE TITLE
How do you enter a stock split?

### ISSUE THREAD

**Issue by JalapenoGremlin** [ledger/ledger#1784]
This isn't a "bug issue" (but possibly a documentation question). So how do I enter a stock split into ledger?

```
2010-01-01 Buy ACME
  Assest:Checking             $-100.00
  Assets:Stocks                     2 ACME @ $50.00
```
In 2015 the stock splits 2 shares for every 1 owned
```
2015-06-30 Acme Split 2x1
   ;; I now own 4 ACME shares 
   ;; Let's say that before the split ACME was at $120.00 
   ;; After the split ACME' is $60/share
   ;; QUESTION...
   ;; How do I enter this?
```
And now I sell
```
2017-03-30  Sell Acme
    Assets:Stock                            - 3 ACME @ $70.00
    Assets:Checking                   $210.00
```

Effectively. 
I purchased 4 "effective" shares of ACME on 2010-01-01 for an "effective price" of $25/share
and sold 3 shares of ACME at $75/share on 2017-03-30. So my capital gains are (210-75) $135.
(Not as worried about the commission and what not. Those have been excluded for purposes of brevity)

**Comment by tbm** [comment]
> 2015-06-30 Acme Split 2x1
>   ;; I now own 4 ACME shares 
>   ;; Let's say that before the split ACME was at $120.00 
>   ;; After the split ACME' is $60/share

Maybe I'm reading too much into what you wrote but it sounds like you want to realise a capital gain here. I don't think a stock split would do that.

Anyway, I will show both scenarios - with a capital gain caused by the split and without.  I think without is what you want (this will get the $135 you mention)

# without

```
2010-01-01 Buy ACME
  Assets:Stocks                2 ACME @@ $100
  Assets:Checking            -$100.00

2015-06-30 Acme Split 2x1
  Assets:Stocks                4 ACME {$25.00} [2015-06-30]
  Assets:Stocks               -2 ACME {$50.00} [2010-01-01]

2017-03-30  Sell Acme
  Assets:Checking                   $210.00
  Assets:Stocks               -3 ACME {$25.00} [2015-06-30] @ $70
  Income:Capital gains          -$135
```
# with

```
2010-01-01 Buy ACME
  Assets:Stocks                2 ACME @@ $100
  Assets:Checking            -$100.00

2015-06-30 Acme Split 2x1
  Assets:Stocks                4 ACME {$60.00} [2015-06-30] @ $60
  Assets:Stocks               -2 ACME {$50.00} [2010-01-01] @ $120
  Income:Capital gains          -$140

2017-03-30  Sell Acme
  Assets:Checking                   $210.00
  Assets:Stocks               -3 ACME {$60.00} [2015-06-30] @ $70
  Income:Capital gains          -$30
```

**Comment by JalapenoGremlin** [comment]
So easy. I guess. I was not trying to realize any gains in 2015. Just recording the fact that it split.


Thanks for your help and with the corrections with the @@. I've just started tracking "other currencies/stocks" with ledger, but have been using it for home currency ($) for a while now.

**Comment by JalapenoGremlin** [comment]
Here's what I ended up doing. I think this keeps the record correctly. Maybe this is all there is to it? 
Still annoying to have to repeat the information from earlier, but it does keep the "only new entries go into a ledger" philosophy.
```
2013/06/30 Wile E. Coyote
  Assets:Brokerage                    18 ACME @@ $313.37
  Assets:Brokerage:Cash         $-313.37

2013/12/31 Wile E. Coyote
  Assets:Brokerage                    28 ACME @@ $432.32
  Assets:Brokerage:Cash         $-432.32

2014/07/01 Wile E. Coyote
  Assets:Brokerage                    14 ACME @@ $373.37
  Assets:Brokerage:Cash         $-373.37

2014/07/17 Wile E. Coyote 2-for-1 split
  Assets:Brokerage                   -18 ACME [2013/06/30] @@ $313.37
  Assets:Brokerage                   -28 ACME [2013/12/31] @@ $432.32
  Assets:Brokerage                   -14 ACME [2014/07/01] @@ $373.37
  Assets:Brokerage                    36 ACME [2013/06/30] @@ $313.37
  Assets:Brokerage                    56 ACME [2013/12/31] @@ $432.32
  Assets:Brokerage                    28 ACME [2014/07/01] @@ $373.37
```

**Comment by tbm** [comment]
looks correct to me

**Comment by ckeschnat** [comment]
I know this is old and closed, but I had this thread as a comment in my ledger file, so I'm trying here.

I entered this in 2022 and so far had no issues:

```
2022-08-03 ACME split 4x1
    Assets:depot                                                                28 "ABCDEF" {160.00 EUR} [2022-08-03]
    Assets:depot                                                                -7 "ABCDEF" {40.00 EUR} [2021-02-25]
```

Now my operating system updated ledger from from 3.3.2 to 3.4.1 and the split does not work anymore:

```
> 2022-08-03 ACME split 4x1
>     Assets:depot                                                                28 "ABCDEF" {160.00 EUR} [2022-08-03]
>     Assets:depot                                                                -7 "ABCDEF" {40.00 EUR} [2021-02-25]
Unbalanced remainder is:
         4200.00 EUR
Amount to balance against:
28 "ABCDEF" {160.00 EUR} [2022/08/03]
Error: Transaction does not balance
```

**Comment by jw-pos** [comment]
@ckeschnat It looks like your transaction is invalid: You are exchanging 7 shares @ 40 EUR (280 EUR basis cost) for 28 shares at 160 EUR (4,480 EUR basis cost). This is why you have 4200 EUR unbalanced. See the newly added test in PR 2494, which shows a correct stock split where the basis costs balance.

**Comment by jwiegley** [comment]
Oops, I meant to make that comment as me. :)

**Comment by ckeschnat** [comment]
Hey @jwiegley thanks, that worked. I guess my entry had always been wrong, but I (and ledger 3.3.2) just didn't notice? I can only guess that I never checked without `--exchange` and the EUR amount was too low to stand out (I checked now - 28 shares show up as expected).

**Comment by jw-pos** [comment]
Yes, new logic was specifically added to support "commodity swaps over a common basis commodity", which now catches this scenario.
