### ISSUE TITLE
^ symbol missing in passphrases on Nano s

### ISSUE THREAD

**Issue by zndtoshi** [ledger/ledger#1785]
When trying to apply a passphrase to a private key the symbol ^ is missing. Would be nice to have it implemented as it shouldn't be too difficult.

**Comment by crazyh** [comment]
> as it shouldn't be too difficult.

It definitely seems like you can do it yourself.

**Comment by tbm** [comment]
This ledger repository is for the command-line accounting tool called ledger.  Not for the hardware ledger you're talking about.

Please report your issue to https://github.com/LedgerHQ/ledger-nano-s
