### ISSUE TITLE
lots not working the way I expected (hoped)

### ISSUE THREAD

**Issue by dncohen** [ledger/ledger#1799]
I'm a newbie to ledger, but have been reading.  I'm unable to get lots to work correctly.  It seems like when I specify a lot, ledger doesn't try to balance that portion of a transaction.  I wonder if that's a bug (or user error).

I'm on fedora and `ledger -version` reports `Ledger 3.1.1-20160111`.

In my test data (below), I'm simulating some crypto trades.  A relatively simple transaction selling "ABC" for USD seems to work ok.  I was hoping ledger would do the right thing if I trade "ABC" for "WTF", but it doesn't balance the transaction the way I've entered it.

I noticed that if I make a transaction that is clearly unbalanced, but specifies a lot, ledger doesn't care that it is unbalanced.  Ledger doesn't complain if I change my third transaction to this:

```
2017/03/01 This transaction is only a debit with no offsetting credit!
           Assets:Crypto        -10 ABC {0.02 USD} [2014/01/01] @ 1 USD
```

If I structure the transaction the way I'd like it to work, ledger does complain that it doesn't balance.  It's as if it is ignoring the first line item in the transaction.

```
2017/03/01 now trade for WTF
           Assets:Crypto        -10 ABC {0.02 USD} [2014/01/01] @ 1 USD
           Exchange:Coinboys    5 WTF @ 2 ABC
```

Here's the complete test I'm trying to run.  I'd appreciate any pointers how to represent these trades.

```
; ledger-cli test for crypto features

; Somebody was giving away ABC, back when it was worth 2 cents.
2014/01/01 receive some ABC
           Assets:Crypto        100 ABC @ 0.02 USD
           Income:AirDrop

; The price of ABC rose to one dollar, I sold one.
2017/02/01 sell ABC
           ; must use "{0.02 USD} [2014/01/01]", "{0.02 USD}" alone does not work with --lots
           Assets:Crypto        -1 ABC {0.02 USD} [2014/01/01] @ 1 USD
           Exchange:Coinboys    1 USD
           Income:Capital gains

; So far, so good. (With some trouble figuring out how to name a lot.)

; I'd like to represent a trade not involving USD.  Having trouble
; here.  I haven't figured out how to make it balance...

; Then I traded for some other crypto, worth say $2.
2017/03/01 now trade for WTF
           Assets:Crypto        -10 ABC {0.02 USD} [2014/01/01] @ 1 USD
           Exchange:Coinboys    5 WTF @ 2 ABC      ; maybe should be "... @ 2 USD"
           FIXME               ; ledger calculates "-10 ABC"

; ledger balance for "FIXME" becomes "-10 ABC".  (Or if I I say "5 WTF @ 2 USD, it calculates "-10 USD").
; The desired result is that the final trade balances.  Ideally, FIXME would be a capital gain of $9.80.
```

**Comment by dncohen** [comment]
An update, and a more concise description of the problem...

Now, I'm trying with a build from source, `ledger --version` shows:
`Ledger 3.1.3-20190331`

Here's two transactions:

```
; Somebody was giving away ABC, back when it was worth 2 cents.
2014/01/01 receive some ABC
           Assets:Crypto        100 ABC @  0.02 USD
           Income:AirDrop

; The price of ABC rose to one dollar, I sold one.
2017/02/01 sell ABC
           Assets:Crypto        -1 ABC {0.02 USD} [2014/01/01] @ 1 USD
           Exchange:Coinboys    1 USD
           Income:Capital gains   -0.98 USD
```

`bal --lots` shows what I expect:

```
99 ABC {0.02 USD} [14-Jan-01]  Assets:Crypto
            1.00 USD  Exchange:Coinboys
           -2.98 USD  Income
           -2.00 USD    AirDrop
           -0.98 USD    Capital gains
--------------------
99 ABC {0.02 USD} [14-Jan-01]
           -1.98 USD
```

But if I change the second transaction, asking ledger to calculate the capital gain, I get different numbers:

```
; Somebody was giving away ABC, back when it was worth 2 cents.
2014/01/01 receive some ABC
           Assets:Crypto        100 ABC @  0.02 USD
           Income:AirDrop

; The price of ABC rose to one dollar, I sold one.
2017/02/01 sell ABC
           Assets:Crypto        -1 ABC {0.02 USD} [2014/01/01] @ 1 USD
           Exchange:Coinboys    1 USD
           Income:Capital gains
```

```
99 ABC {0.02 USD} [14-Jan-01]  Assets:Crypto
               1 USD  Exchange:Coinboys
              -3 USD  Income
              -2 USD    AirDrop
              -1 USD    Capital gains
--------------------
99 ABC {0.02 USD} [14-Jan-01]
              -2 USD
```

It seems to me that the presence of this line in the second transaction:
`           Assets:Crypto        -1 ABC {0.02 USD} [2014/01/01] @ 1 USD`

Somehow tells ledger "ignore this line, and this transaction does not need to balance precisely."

Am I misunderstanding something?

**Comment by tbm** [comment]
Your display precision doesn't include digits.

Add

```
D 0.01 USD
```

to the top of the file and you'll see

```
           -0.98 USD    Capital gains
```

1 USD is just rounding because your display precision doesn't have digits.

You can influence the display precision by changing

```
           Exchange:Coinboys    1 USD
```

to
```
           Exchange:Coinboys    1.00 USD
```

Then you don't need the `D`.

**Comment by dncohen** [comment]
Wow, that's an important piece of information! Thanks.
