### ISSUE TITLE
Can we have per-posting codes?

### ISSUE THREAD

**Issue by daraul** [ledger/ledger#1813]
I hope I'm not stepping on any toes here, but I ran into this situation the other day. When a subscription was paid for online (in this case Netflix). 

```
2019/07/26 * Netflix  ; Netflix July Subscription
    assets:Bank                  -2373.84 GYD  (#1234567)
    expenses:subscriptions:Netflix      1 "Netflix Monthly Subscription" { 10.99 USD } (#1234-1234-5531-5311)
```

I wanted to keep both 'codes' for both sides of the transaction: the netflix receipt ID, and my bank's transaction ID, but that didn't work, and ended up giving me some odd errors. I ended up putting the codes in comments for each posting like so:

```
2019/07/26 * Netflix  ; Netflix July Subscription
    assets:Bank                  -2373.84 GYD  ; #1234567
    expenses:subscriptions:Netflix      1 "Netflix Monthly Subscription" { 10.99 USD }  ; #1234-1234-5531-5311
```

I believe this might be a use-case we run into more often than not, and I like the ability to keep the identifiers for both sides of this transaction. Is it possible some other way? Have I missed something in docs?

**Comment by tbm** [comment]
You can have meta-data on postings.  That's how people would usually solve this.

**Comment by tbm** [comment]
Example:

```
2019/07/26 * Netflix  ; Netflix July Subscription
    assets:Bank                  -2373.84 GYD  ; Ref: 1234567
    expenses:subscriptions:Netflix      1 "Netflix Monthly Subscription" { 10.99 USD }  ; Ref: 1234-1234-5531-5311
```

```
ledger -f d reg -l "tag('Ref') =~ /12345/"
2019-07-26 Netflix                                   assets:Bank                                                 -2373.84 GYD             -2373.84 GYD
ledger -f d reg -l "tag('Ref') =~ /1234-/"
2019-07-26 Netflix                                   expenses:subscriptions:Netflix                  1 "Netflix Monthly Subscription" 1 "Netflix Monthly Subscription"
```

**Comment by jwiegley** [comment]
Meta-data is the way.
