### ISSUE TITLE
Please follow the XDG Base Dir Spec

### ISSUE THREAD

**Issue by billop** [ledger/ledger#1820]
Although ledger allows specifying any file for configuration, it would be nice to have sane defaults that follow the [spec](https://wiki.archlinux.org/index.php/XDG_Base_Directory) and falls back to the legacy default locations.

**Comment by tbm** [comment]
That would be nice.  Do you think you can work on a patch?

**Comment by tbm** [comment]
@billop there's a PR for this now, see #1960

**Comment by jwiegley** [comment]
Now merged. Thank you!

**Comment by tbm** [comment]
Implemented in c79674649dee7577d6061e3d0776922257520fd0
