### ISSUE TITLE
macOS builds fail due to outdated homebrew

### ISSUE THREAD

**Issue by twrightsman** [ledger/ledger#1824]
See the build log [here](https://travis-ci.org/ledger/ledger/jobs/581488310#L96).

This is discussed a bit [here](https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798/9), but it seems the Travis CI homebrew addon is currently still broken.

homebrew may need to be installed as part of the build process for now until the addon is fixed.

**Comment by twrightsman** [comment]
Telling the homebrew addon to update itself before every build adds a lot of extra build time but installs Boost 1.71, which doesn't work (see https://github.com/ledger/ledger/pull/1823) with the current build system.

**Comment by tbm** [comment]
Is this still an issue @twrightsman ?

**Comment by mn200** [comment]
Not clear to me if this is related, but my brew install of boost is 1.72 on Catalina, and I am getting clang errors of the form:
```
/usr/local/include/boost/math/special_functions/fpclassify.hpp:552:17: error: 
      no member named 'isnan' in namespace 'std'; did you mean simply
      'isnan'?
        return (std::isnan)(x);
```
stemming from `ledger/system.hh`

**Comment by tbm** [comment]
@mn200 do you still see this?

@twrightsman is this still there?

**Comment by q3aiml** [comment]
I think we're good to close this. The report concerns travis which has been building for some time and is now passing tests.

**Comment by tbm** [comment]
closing as per @q3aiml's comment.
