### ISSUE TITLE
import does not work with multiple wildcards

### ISSUE THREAD

**Issue by ennob** [ledger/ledger#1830]
The 'import' keyword can be used to import other ledger files into the one that is currently being processed, however it does not work with multiple wildcards. For example, the following

`import subdir/*/*.ledger`

should result in all the following files being imported:
```
subdir/A/abc.ledger
subdir/A/def.ledger
subdir/B/ghi.ledger
```
but instead I get an error.

**Comment by tbm** [comment]
This is a known issue, see issue #1214
