### ISSUE TITLE
When upgrading from Alpine 3.10 to 3.11, getting so:libmpfr.so.4 (missing)

### ISSUE THREAD

**Issue by alberto56** [ledger/ledger#1849]
To reproduce, install Docker and create a Dockerfile with:

    FROM alpine:3.10
    # Add the edge and testing repositories.
    RUN echo "http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
         echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
         apk update && apk upgrade
    # Install ledger and dependencies.
    RUN apk add ledger

Then, in the directory where the Dockerfile resides, run:

    docker build . 

Then, change your Dockerfile to 

    FROM alpine:3.11
    # Add the edge and testing repositories.
    RUN echo "http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
         echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
         apk update && apk upgrade
    # Install ledger and dependencies.
    RUN apk add ledger

And, again, run:

    docker build . 

The result is:

    ...
    Step 3/4 : RUN apk add ledger
     ---> Running in 404383fb1671
    ERROR: unsatisfiable constraints:
      so:libmpfr.so.4 (missing):
        required by: ledger-3.1.3-r1[so:libmpfr.so.4]
    The command '/bin/sh -c apk add ledger' returned a non-zero code: 2

**Comment by tbm** [comment]
did you find out what the problem is?  Is this still there with latest ledger?

**Comment by alberto56** [comment]
Seems to work now! 

https://app.circleci.com/pipelines/github/dcycle/docker-ledger/23/workflows/b1bce3b2-e63e-436e-9abb-2512a5ac91d3/jobs/24

I'm closing this issue
