### ISSUE TITLE
Virtual account created by automatic transaction shouldn't be equal to 0 in assertion

### ISSUE THREAD

**Issue by pcooksey** [ledger/ledger#1855]
I'm trying to use automatic virtual transactions to capture values and then use an assert to test the values afterward. Maybe this isn't possible? Basically, I was trying to do an assertion that `paychecks * some % == retirement` however it seems that the virtual account is still zero when I test the assertion.  

Simple test case:
```ledger
= Income:Salary
    (Salary)                                                             -1

2020/01/10  Opening Balances
    Bank                                                               $300
    Income:Salary                                                    
    
assert account("Salary").amount == 0
```

```
$ledger -f test.ledger reg
20-Jan-10 Opening Balances        Bank                                $300          $300
                                  Income:Salary                      $-300             0
                                  (Salary)                            $300          $300
```

I expected it to fail but it seems the virtual account is still zero when the assert is tested.

Version: Ledger 3.1.2-20160801, the command-line accounting tool.

**Comment by tbm** [comment]
Please upgrade to 3.1.3.  This works as you expect for me on 3.1.3

**Comment by tbm** [comment]
```
Error: Assertion failed: account("Salary").amount == 0
```

whereas this works:

```
assert account("Salary").amount == $300
```

**Comment by pcooksey** [comment]
Okay, I think I'll have to build it tonight then since I'm on Ubuntu 18.04 with the only package being 3.1.2. Alos, thanks for the quick response. We can probably close this ticket or wait until I have tested it.

**Comment by pcooksey** [comment]
`assert account("Salary").amount == 0`:
```
While parsing value expression:
  account("Salary").amount ==

Error: == operator not followed by argument
```

` assert (account("Salary").amount == 0)`:
```
Error: Assertion failed: (account("Salary").amount == 0)
```

I tested some things and I either have to add a space after the `0` or a newline for it to work correctly without the parentheses. I guess this is a corner case with an assert at the very end of the file.

Version: Ledger 3.1.3-20190331

**Comment by tbm** [comment]
@pcooksey I think you're describing issue #516 right?

**Comment by pcooksey** [comment]
Yup that looks like it. I don't know your policy but you can probably close this issue . Thanks again for answering my question. Also, Ledger is pretty awesome!

**Comment by tbm** [comment]
Closing since there's another ticket already.
