### ISSUE TITLE
! is a unary operator, not binary or ternary

### ISSUE THREAD

**Issue by crowsonkb** [ledger/ledger#1868]
The Ledger [documentation](https://github.com/ledger/ledger/blob/master/doc/ledger3.texi#L8076) says:

> The binary and ternary operators, in order of precedence, are:
```
1. * /
2. + -
3. ! < > =
4. & | ?:
```

It then lists the unary operators:

`not neg`

But as far as I can tell, by examining the expression and compiled trees produced by the `args` command, `!` is just an alias for `not`. It should be listed as a unary operator and the documentation regarding the precedence table should be fixed. I am not sure enough yet how Ledger operator precedence works in reality to try to correct the precedence table documentation myself, though.

**Comment by tbm** [comment]
I think this one is for @jwiegley.  But I don't think there's much value in saying the type of operator, so I replaced "The binary and ternary operators, in order of precedence" simply with "The operators, in order of precedence".  If @jwiegley has a better fix, he can commit.

I added `!` as an alternative to `not` in the next subsection.

Thanks.
