### ISSUE TITLE
Wiki page outdated

### ISSUE THREAD

**Issue by jcguu95** [ledger/ledger#1870]
This is an issue about this [wikipage](https://github.com/ledger/ledger/wiki/CSV-Import). Softwares recommended there are categorized based on the date of the latest commit. Some of the information is out of date. I checked all of them manually and here's the result:

### expired (last commit >= 12 months)
https://github.com/dimagog/mint2ledger
https://github.com/manishrjain/into-ledger
https://github.com/quentinsf/icsv2ledger

### refreshed (last commit <  12 months)
https://github.com/cantino/reckon

**Comment by tbm** [comment]
I made the updates, thanks

But it's a wiki. Next time you can edit the page yourself.

**Comment by jcguu95** [comment]
Didn't know that! Thanks for the tip and your work :)
