### ISSUE TITLE
Standard input -- handling multiple files

### ISSUE THREAD

**Issue by jcguu95** [ledger/ledger#1872]
First of all, `ledger` is a great software! Thanks for all the hard work. I have been playing with it for 2 whole days, and finally got my 3-year-old messy financial history straight!!!

It meets all my need. However, one thing I notice that might help is to allow `ledger` to read standard input.

```
$ cat *.dat  |  ledger balance
```

This could partially solve the double-wildcard issue mentioned [here](https://github.com/ledger/ledger/issues/1214) by running

```
$ cat $(ls ./*/*.dat)  |  ledger balance
```

**Comment by peterkeen** [comment]
Use -f - to read stdin.

**Comment by peterkeen** [comment]
Use “-f -“ to read stdin.

**Comment by jcguu95** [comment]
! Ah! Right! I did remember reading this in the full document.. :( Sorry for that.
