### ISSUE TITLE
feature request: hledger-lik `cur:`

### ISSUE THREAD

**Issue by samm81** [ledger/ledger#1889]
Although I keep track of other commodities (digital assets) most of the time I am just interested in seeing reports using my base currency ($). Hledger has the `cur:$` option to limit to just one currency.

**Comment by tbm** [comment]
You can do this in ledger: -l "commodity == '$'"

**Comment by samm81** [comment]
Oh, awesome! I combed through the docs, and even the mailing list, and never found anything about this. Having to use the `--limit` flag, seems a bit unrecoverable, it might be nice to have a dedicated flag just for limiting the commodity.

Anyways, I'll mark this closed.
