### ISSUE TITLE
Specifying Python version when running cmake

### ISSUE THREAD

**Issue by ngleb** [ledger/ledger#1893]
Hi!

I'm trying to build 3.2.0 with Python support. All dependencies are installed, however I have issue with adding Python support.

When running `cmake -DUSE_PYTHON=yes .`, it does detect Python, but only the latest version installed which is 3.8.2, but the main version I have is python 3.7 and Boost is also built only with python 3.7.

I tired passing `-DPYTHON_EXECUTABLE=/usr/bin/python3.7` but that doesn't work:
[ledger-1.log](https://github.com/ledger/ledger/files/4573848/ledger-1.log)

If I remove Python 3.8, then `cmake -DUSE_PYTHON=yes .` finishes without errors:
[ledger-2.log](https://github.com/ledger/ledger/files/4573847/ledger-2.log)

I'm on Gentoo, the following deps are installed:
- Python 3.6, Python 3.7 (this is the main version that is used by the system and is supported by Boost), Python 3.8,
- GCC 9.3.0
- Cmake 3.16.5
- ledger 3.2.0

Is there another option that could help?

**Comment by ngleb** [comment]
I found was was causing the issue.

ledger sources has its own FindPython cmake module. If I remove this module, and cmake uses its own modules, then I can build ledger with the following command:

`cmake -DPython_EXECUTABLE=/usr/bin/python3.7 -DPython_INCLUDE_DIR="/usr/include/python3.7m" -DUSE_PYTHON=yes .`

**Comment by ngleb** [comment]
It looks like these options were added in 3.16, but FindPython module in ledger sources is from 3.15:
https://github.com/Kitware/CMake/commit/06d9e67fbd2b2dfc9cba12327866b2f73eab8a18#diff-19d61b7db7059e6b1e00d0e31d827b73

**Comment by tbm** [comment]
@q3aiml can you look into this?

**Comment by tbm** [comment]
> It looks like these options were added in 3.16, but FindPython module in ledger sources is from 3.15

Can you update the FindPython module in ledger and submit a PR?

**Comment by ngleb** [comment]
> Can you update the FindPython module in ledger and submit a PR?

That's strange, but tests are failing as new FindPython can't properly locate Python include path now and builds are failing. It can be manually specified in CMake arguments like this, but it has to be interpreter and include dirs together:
`cmake . -DPython_EXECUTABLE=/usr/bin/python3.7 -DPython_INCLUDE_DIR="/usr/include/python3.7m" -DUSE_PYTHON=yes`
