### ISSUE TITLE
--invert breaking change

### ISSUE THREAD

**Issue by clonejo** [ledger/ledger#1895]
In ledger 3.2.0 (presumably caused by #1804) `--invert` has no effect anymore on at least `%(amount)`, `%(amount_expr)` and `%(total)` in a custom format string.

Not sure about ledger's stability guarantees, but this change could have cost me hours of additional work sending people money back I wrongfully charged them, if I had not noticed. Luckily, no harm done :)

To replicate the old behavior, eg. get inverted amounts and totals, the solution seems to be using `%(display_amount)` and `%(display_total)`.

Btw the documentation on the website is still for 3.0.

**Comment by tbm** [comment]
Adding @jwiegley

**Comment by jwiegley** [comment]
@clonejo That is indeed terrible. Do you have a simple test case that shows your problem? I use `--invert` every day, but haven't noticed any breakage yet. Once I can reproduce it here, I can fix it this weekend.

**Comment by tbm** [comment]
@clonejo do you have a testcase?

**Comment by clonejo** [comment]
### Ledger 3.2.0-20200501

```bash
$ echo "2020-01-01\n  foo  10€\n  bar  -10€" | ledger -f - reg         
20-Jan-01 <Unspecified payee>   foo                             10€          10€
                                bar                            -10€            0

$ echo "2020-01-01\n  foo  10€\n  bar  -10€" | ledger -f - reg --invert
20-Jan-01 <Unspecified payee>   foo                            -10€         -10€
                                bar                             10€            0
```

```bash
$ echo "2020-01-01\n  foo  10€\n  bar  -10€" | ledger -f - reg --format='%(account) %4(amount) %4(amount_expr) %4(total)        %4(display_amount) %4(display_total)\n'
foo  10€  10€  10€         10€  10€
bar -10€ -10€    0        -10€    0

$ echo "2020-01-01\n  foo  10€\n  bar  -10€" | ledger -f - reg --format='%(account) %4(amount) %4(amount_expr) %4(total)        %4(display_amount) %4(display_total)\n' --invert
foo  10€  10€  10€        -10€ -10€
bar -10€ -10€    0         10€    0
```

I don't have the older version of ledger quickly at hand, do you need an example of the old behavior?

**Comment by tbm** [comment]
Thanks for this testcase.

Old behaviour was:

```
65603:tbm@jirafa: ~] echo "2020-01-01\n  foo  10€\n  bar  -10€" | ledger -f - reg --format='%(account) %4(amount) %4(amount_expr) %4(total)        %4(display_amount) %4(display_total)\n'

foo  10€  10€  10€         10€  10€
bar -10€ -10€    0        -10€    0
65604:tbm@jirafa: ~] echo "2020-01-01\n  foo  10€\n  bar  -10€" | ledger -f - reg --format='%(account) %4(amount) %4(amount_expr) %4(total)        %4(display_amount) %4(display_total)\n' --invert
foo  10€ -10€ -10€        -10€ -10€
bar -10€  10€    0         10€    0
```

**Comment by jwiegley** [comment]
@tbm This was broken in 9ad0dcc85a3ec59a1dd23f36964d083cf59bd7a9

```
commit 9ad0dcc85a3ec59a1dd23f36964d083cf59bd7a9
Author: John Wiegley <johnw@newartisans.com>
Date:   Fri Jul 5 13:01:11 2019 -0700

    Change --invert to invert displayed amounts and totals, not amounts
```

I think again we should just revert and then explore the right fix, with regression tests to prevent this from breaking again.

**Comment by jwiegley** [comment]
I ran into a problem with amount inversion "inverting the inverted amount" when doing composite reports like `--gains`.

**Comment by jwiegley** [comment]
Because there are times when we calculate based on a series of amounts (which are now inverted), and then we derive an aggregate which is then inverted again, so that the final result is not inverted. It makes the flag appear useless in those cases.

**Comment by clonejo** [comment]
Thank you, good work!
