### ISSUE TITLE
Slow performance with upgrade to 3.2

### ISSUE THREAD

**Issue by dmp1ce** [ledger/ledger#1907]
From IRC:

> I have a "bal not \("[xxx]"\) command which is quite slow. It takes about 20 seconds when it used to only take less than a second.
> I just downgraded to version 3.1.3 on Arch Linux and the same command takes less than 1 second. :/

Other command which do not have the "not" command seem to be performing normally.

I'll work on a way a standard way to reproduce, but I thought it was worth reporting in case anyone else is having an issue.

**Comment by jwiegley** [comment]
@dmp1ce Are you able to test if a6a58af2 is the culprit? That is:

```
git clone git@github.com:ledger/ledger
cd ledger
git checkout v3.2.0
git revert a6a58af2
mkdir build
./acprep debug
cd build
make
<now use the Ledger that's in this directory>
```

**Comment by jwiegley** [comment]
Also, if you can use `print --anon` to make an anonymized test case that demonstrate the slow-down, I'd be happy to do the performance analysis here. Git bisect is especially handy at tracking down which commit introduced this regression.

**Comment by tbm** [comment]
@dmp1ce where do you get ledger from? I guess Arch?

Make sure that you're not comparing a ledger 3.1 without debugging enabled and ledger 3.2.0 with debugging.

**Comment by dmp1ce** [comment]
Yeah, I'm using 3.2.0 from pacman official repositories.

**Comment by dmp1ce** [comment]
I'll try out these suggestions tomorrow. Thanks guys!

**Comment by jwiegley** [comment]
Great, I'd love to see a fix for this in @tbm 's upcoming release.

**Comment by dmp1ce** [comment]
@jwiegley, I tried with commit reverted and had the following results:

```
time ./ledger --no-pager -f index.ledger bal
. . . 
real    0m1.747s    
user    0m1.725s
sys     0m0.020s
```

With version 3.2.0:

```
ledger --version
Ledger 3.2.0-20200501, the command-line accounting tool

Copyright (c) 2003-2019, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.

$ time ledger --no-pager -f index.ledger bal
. . .
real    0m31.808s
user    0m31.736s
sys     0m0.030s
```

**Comment by dmp1ce** [comment]
I tried to use `print --anon` but it created a file which was processed quickly. I'm trying to figure out how to share my data anonymously but haven't come up with anything yet. I think it has something to do with the number of different account and the number of different currency transactions which look like this:

```
2020/01/01 Transaction 1
    A:Account:1                                           1.111 STUFF
    A:Account:2                                            -$3
```

**Comment by jwiegley** [comment]
Oops, pressed wrong button.

@tbm Let's revert that commit and then we can release. I'll move the behavior that's in that commit under a command-line option, at least until a faster method of commodity comparison can be determined.
