### ISSUE TITLE
budget available for future time periods

### ISSUE THREAD

**Issue by chrpinedo** [ledger/ledger#1944]
Hello,

for bugdeting purposes I use two commands that works with current or past time periods, for example:

- `ledger --budget -p "this month" reg ^expenses`
- `ledger budget -p "this month" ^expenses`

However, it doesn't work for future time periods. No output is displayed for time periods such as `-p "next month"` or `-p "next year"`. Even, the `-p "this year"` only displays the fulfillment of the budget until the current date not for all the current year (including the future months of this year).

What I would like to know is: "what is my available budget for the next month?"

I think this is a missing feature and it is different from `--forecast`. I don't want to know the status of one account at a given time according to my budget forecast. I want to know the budget forecast for that time period.

**Comment by chrpinedo** [comment]
I found in reddit that `--now` argument can be used. For example, `ledger budget -p "this month" -now august ^expenses`. I close the issue. Regards.

**Comment by tbm** [comment]
Can you check if this is covered in the ledger manual: https://www.ledger-cli.org/3.0/doc/ledger3.html

If not, maybe we should re-open the issue and maybe you could contribute something to the documenation.

**Comment by chrpinedo** [comment]
There are some mentions to the "--now" option in the ledger manual. But, perhaps, it would be interesting one example in the section 9.1 to propose its usage to know the budget of future time periods.
