### ISSUE TITLE
I'm not sure how to install scripts 😬

### ISSUE THREAD

**Issue by NatalieGates** [ledger/ledger#1947]
I would like to install the report script located in `contrib/report`

> The script to do this is included in the ledger distribution, and is named contrib/report. Install report anywhere along your PATH, and then use report instead of ledger when doing a register report.

How do I install `report` along my PATH? Can you explain this step-by-step? I'm very new to computer programming.

I used `brew install ledger` and `brew install gnuplot` on Mac OSX

**Comment by tbm** [comment]
* Down from https://raw.githubusercontent.com/ledger/ledger/master/contrib/report
* Save as `report`
* Make it executable: `chmod +x report`
* Run it: `./report ...`

But I'm not sure this script is very useful.

**Comment by NatalieGates** [comment]
Thank you. It produced an error "gnuplot> set terminal x11 persist"

But, you mentioned it might not be useful... my end goal is to visualize my ledger data. Maybe someone could offer a solution for this? Something that would also allow me to visualize my budget data?

**Comment by tbm** [comment]
It would be best for you to post to the ledger mailing list: ledger-cli@googlegroups.com in order to get input from other users.
