### ISSUE TITLE
Incorrect .ledgerrc syntax in documentation

### ISSUE THREAD

**Issue by intdfdx** [ledger/ledger#1954]
To modify the input date format, I must enter the following in ~/.ledgerrc:
--input-date-format=%m/%d/%Y

This differs from the ENVIRONMENT section in the man page and the online manual (https://www.ledger-cli.org/3.0/doc/ledger3.html#Environment-variables) that suggests the proper syntax would be:
--input-date-format '%m/%d/%Y'

I am using Ledger 3.1.2-20190205 on Gentoo, if that matters.

**Comment by simonmichael** [comment]
To be clear, the problem is the quotes around the option argument. .ledgerrc is probably parsing them as part of the argument.

**Comment by tbm** [comment]
This works and is the easiest:

```
--input-date-format %m/%d/%Y
```

**Comment by tbm** [comment]
While the manual could be clearer, I don't see anything there that's actually *wrong*.

**Comment by tbm** [comment]
> While the manual could be clearer, I don't see anything there that's actually wrong.

@intdfdx can you point me to the docs that are wrong?

**Comment by tbm** [comment]
I'll add an example to the docs to clarify.
