### ISSUE TITLE
Exchange flag for unicode currency not working under Windows

### ISSUE THREAD

**Issue by ftwang** [ledger/ledger#1986]
I can't seem to get the exchange flag working under Windows, for currencies represented using unicode characters.

**foreign_currency.ledger**
```
commodity £
  default

2013/04/01 Transaction Paid Using USD
  Expenses         100 USD @ (£ 1/2)
  Assets

2013/04/02 Transaction Paid Using £
  Expenses        £100
  Assets
```

**Expected Results (Working on MacOSX)**
```
> ledger -f foreign_currency.ledger balance --exchange £
               £-150  Assets
                £150  Expenses
--------------------
                   0
```

**Unexpected Results (Windows 10)**
```
> ledger.exe -f foreign_currency.ledger balance --exchange £
               £-150  Assets
             100 USD
                £100  Expenses
--------------------
             100 USD
                £-50
```

I have tried changing the code page to Unicode for the Windows command prompt
```
> chcp 65001
```
but still the same results.

If I set the exchange flag to USD, the results are correct.
```
> ledger.exe -f foreign_currency.ledger balance --exchange USD
            -300 USD  Assets
             300 USD  Expenses
--------------------
                   0
```
Any ideas what I'm doing wrong under Windows?

I'm using the pre-compiled Windows Ledger binary v3.2.1 from https://github.com/FullofQuarks/Windows-Ledger-Binaries/releases/tag/v3.2.1

**Comment by tbm** [comment]
I suspect that despite setting `chcp 65001` the pound symbol from the command line is getting garbled.  At least that's my hunch.

I don't know what you can do about... apart from using `GBP` instead of the symbol.

**Comment by tbm** [comment]
I'm copying @coonce who may have run into this issue because there were some changes in #1971 that might have fixed this (but they were reverted because of introducing a new dependency).

**Comment by tbm** [comment]
see https://github.com/ledger/ledger/pull/1971/commits/c35a8387171488e47e8a6363261b5b152f21ba0c

**Comment by tbm** [comment]
@ftwang can you try the master branch from GitHub and report if this is working now.  The fix from @coonce should have fixed this.
