### ISSUE TITLE
Tracking cashback?

### ISSUE THREAD

**Issue by thoelze1** [ledger/ledger#1988]
I'm brand new to ledger. One of the things I want it to do is track cash back. This seems like a perfect use case for automated transactions. However, my credit card company offers different levels of cash back depending on the expense. This means that the automated transaction would need to check multiple postings for each transaction before adding its posting: *If* a transaction with a debit from my credit card also contains one type of expense, then the automated transaction should add a posting for *one* level of cash back. *Otherwise*, the automated transaction should add a posting for a *different* level of cash back. In pseudocode, something like this:

```
= Liabilities:MasterCard and Expenses:Gas
    Assets:Cash Back                           -0.02
    Equity:MasterCard                           0.02
```

and

```
= Liabilities:MasterCard and not Expenses:Gas
    Assets:Cash Back                           -0.01
    Equity:MasterCard                           0.01
```

I can't see a way in the documentation to do this, which makes me think that perhaps this isn't a good use case for automated transactions. Am I missing something? What other ledger functionality is at my disposal?

**Comment by tbm** [comment]
I'm not a fan of autoamted transactions but it can be done:

```
= Liabilities:MasterCard and expr "any(account =~ /Expenses:Gas/)"
    Assets:Cash Back                           -0.02
    Equity:MasterCard                           0.02

= Liabilities:MasterCard and expr "not any(account =~ /Expenses:Gas/)"
    Assets:Cash Back                           -0.01
    Equity:MasterCard                           0.01
```
