### ISSUE TITLE
Alphanumeric commodity specifiers

### ISSUE THREAD

**Issue by OJFord** [ledger/ledger#1992]
I tried to use an [ISIN](https://en.wikipedia.org/wiki/International_Securities_Identification_Number) as a commodity specifier (since tickers can be ambiguous) but it gives an error due to the numbers: 
> Error: Unexpected char '0' (Note: inline math requires parentheses)

After a couple of guess attempts at escaping it (e.g. `... 123 '<alphanumberic string>' @ ...`) I found [in the docs](https://www.ledger-cli.org/3.0/doc/ledger3.html#Commodities-and-Currencies) that it's not allowed:
> The commodity may be any non-numeric string that does not contain a period, comma, forward slash or at-sign.

Could I suggest that non-numeric be relaxed to alpha-numeric? Or that we have some way of escaping/forcing it to be interpreted as a commodity, such as quoting it as above?

Many thanks.

**Comment by tbm** [comment]
This works fine, as long as you used a quoted commodity:

```
2020-01-01 * Test
    Assets:Investments        1 "LU0292107645" @ 10.00 EUR
    Equity:Opening balance
```

**Comment by simonjpascoe** [comment]
Side note: ISINs are not market specific, they can ambiguous as well (e.g. HSBC Hong Kong and HSBC London share the same ISIN).

**Comment by OJFord** [comment]
@tbm Thanks! It seems I didn't try _double_ quotes... 🤦🏻 The docs could do with an update then though, I can't find a mention of that.

@simonjpascoe I think that's just because HSBC is cross-listed in HK & London, so it's the same security (price should track w.r.t.  GBX/HKD) and thus the ISIN uniquely identifies 'both'? It's a good point, but I think for the distinction to matter you'd have to be holding both, and other than trying to profit on the lag between prices (not investment advice! 😄) I'm not sure why that would arise?

**Comment by simonjpascoe** [comment]
They trade independently, not 100% the same but supposed to reflect the same _amount_ of HSBC in the share (subject to a scaling factor). The prices are going to reflect each other. You can hold both, if you _really_ wanted to, but just a general note for others reading for completeness.
(I have tried to hold a local + adr before, but the end didn't, but those have different ISIN anyhow...).

**Comment by tbm** [comment]
@OJFord I was just looking to see if the documentation needs to be clarified but there is an example:

> And yet, any of these may appear in a commodity name if it is surrounded by double quotes, for example:
> 100 "EUN+133"

**Comment by OJFord** [comment]
@tbm So there is, thanks, I hadn't seen that, it was the sentence:
>  The commodity may be any non-numeric string that does not contain a period, comma, forward slash or at-sign.

that made me think it couldn't be.

A related issue by the way is that quoted commodities appear in output, `csv` & `xml` for example, with quotes. Which of course is inappropriate since then whatever they're being passed to is interpreting them as strings anyway, so they are parsed (correctly) as strings containing quotes.
