### ISSUE TITLE
Assertion error if multiple commodities are in one posting

### ISSUE THREAD

**Issue by Christoph-D** [ledger/ledger#1998]
In some cases, multiple commodities in the same posting trigger an assertion error. A minimal example:

```
2021-01-02 Convert cost basis to EUR (1 EUR = 1 USD)
    Assets            -1 Stock {100 USD} [2021-01-01]
    Assets             1 Stock {100 EUR} [2021-01-01]
    Equity
```

```
$ ledger -f test.leder bal
While parsing file "[...]/test.leder", line 4:
Error: Assertion failed in "[...]/src/commodity.cc", line 551:int ledger::commodity_t::compare_by_commodity::operator()(const ledger::amount_t*, const ledger::amount_t*) const: false
```

This regression was caused by commit 501fbc08ae5493db77bb34f4c4fbe1f3a3bc14e3 ( @jwiegley ) "Change compare_by_commodity to return an integer", because the commit did not only change the return type, it also changed the function's behavior to not always return after the recursive call to `commodity_t::compare_by_commodity()`.

**Comment by tbm** [comment]
Fixed in b155f8928c6a33af42f859b27c83639b72517f5e by @Christoph-D
