### ISSUE TITLE
docker latest not found

### ISSUE THREAD

**Issue by panthia** [ledger/ledger#2000]
docker pull dcycle/ledger
Using default tag: latest
Error response from daemon: manifest for dcycle/ledger:latest not found: manifest unknown: manifest unknown

**Comment by tbm** [comment]
@alberto56 can you comment on this?

**Comment by tbm** [comment]
@panthia please report this at https://github.com/dcycle/docker-ledger/   - this is where the ledger docker image is created.

**Comment by alberto56** [comment]
As documented in https://github.com/dcycle/docker-ledger/issues/11, please use the tag "1", not "latest":

    $ docker pull dcycle/ledger:latest
    Error response from daemon: manifest for dcycle/ledger:latest not found: manifest unknown: manifest unknown
    $ docker pull dcycle/ledger:1
    1: Pulling from dcycle/ledger
    4c0d98bf9879: Pull complete 
    e70c545db2ab: Pull complete 
    633c509f9c73: Pull complete 
    Digest: sha256:d3d738183c58f5876be24b05e2b6c8e7bab6fb0a1a8861c780784396f0140846
    Status: Downloaded newer image for dcycle/ledger:1
    docker.io/dcycle/ledger:1

**Comment by panthia** [comment]
I did try the first example but that did not work either. The pull command that I copied was from the docker site https://hub.docker.com/r/dcycle/ledger/

I don't see anything in the readme about downloading examples but I did do that based on the information on the docker page. 

Here is what happens when I try to run the first example. 

```
docker run --rm -v $PWD/examples:/data dcycle/ledger:1 -f /data/sample.dat reg
Error: Cannot read journal file "/data/sample.dat"
```

I then tried changing permissions to be sure that was not the problem but had the same issue. I also copied and pasted the sample.dat once again to be sure that was not the issue either. 

```
~/data$ ls -l sample.dat
-rwxrwxrwx 1 floyd floyd 1651 Feb  8 08:19 sample.dat
```
I also tried the drew4.dat file with the same result. 

`docker run --rm -v $PWD/examples:/data dcycle/ledger:1 -f /data/drewr3.dat reg
Error: Cannot read journal file "/data/drewr3.dat"`

I don't understand the docker run command since docker run --help says   'rm   Remove one or more containers'

Not sure what I am doing wrong.

**Comment by alberto56** [comment]
That's because you need to have a file called ./examples/sample.dat.

For example, let's say you have a local file called /Users/me/Desktop/some-somefolder/sample.dat that you want to manage, you can run this:

    docker run --rm -v /Users/me/Desktop/some-somefolder:/data dcycle/ledger:1 -f /data/sample.dat reg

The -v parameter shares the local /Users/me/Desktop/some-somefolder directory with /data on the container, so if you are getting "Cannot read journal file /data/drewr3.dat", that means that $PWD/examples/drewr3.dat does not exist on your computer.

If drewr3.dat exists on your local computer but not in the "examples" subdirectory, you can run:

    docker run --rm -v $PWD:/data dcycle/ledger:1 -f /data/drewr3.dat

**Comment by alberto56** [comment]
@panthia your support request is related to https://github.com/dcycle/docker-ledger, so if you need further clarification please open an issue there.

**Comment by panthia** [comment]
Ahh. Thank you so much, that works.

**Comment by tbm** [comment]
Closing
