### ISSUE TITLE
Conda-forge ledger package isn't available

### ISSUE THREAD

**Issue by ThatIsAPseudo** [ledger/ledger#2006]
When trying to install ledger from the conda-forge repo, it fails. The package isn't available anymore, this may be related to the fact that [the current build status on conda-forge/ledger-feedstock](https://github.com/conda-forge/ledger-feedstock#current-build-status) shows "disabled" for every OS. Should I open an issue there instead ?

**Comment by tbm** [comment]
@twrightsman added this. Maybe he knows something.

**Comment by twrightsman** [comment]
Yes, I think this would be more appropriate in the feedstock repository, this isn't a ledger issue. @ThatIsAPseudo Go ahead and ping me again in an issue there and I'll take a look.

**Comment by ThatIsAPseudo** [comment]
Since the conda package is still not available, the relevant section in the Readme should be removed as it can't be installed as of now.

**Comment by ThatIsAPseudo** [comment]
Seems to have been done, closing.

**Comment by twrightsman** [comment]
Thanks for taking care of this and sorry that this happened.

I no longer use `ledger` and need to mark that repository as orphaned, unless someone else wants to maintain it.
