### ISSUE TITLE
Incorrect display of nested account balances if parent balance is zero

### ISSUE THREAD

**Issue by dersuchmann** [ledger/ledger#2009]
There is something off how accounts are displayed **in the balance report** if a parent account is zero AND there is only a single non-zero sub-account. Take this example:
```
2021/01/01 Test
	Left Column:Account A:Sub-Account    100
	Right Column:Account 1:Sub-Account  -100

2021/01/02 Test
	Left Column:Account A               -100
	Right Column:Account 2               100
```

The balance report displays:
```
                 100  Left Column:Account A:Sub-Account
                   0  Right Column
                -100    Account 1:Sub-Account
                 100    Account 2
--------------------
                   0
```

Now my question: What are the amounts of `Right Column:Account 1` and `Left Column:Account A`  (not the sub-accounts)?

From the balance report, we would assume `Right Column:Account 1` is -100, equal to its (only) sub-account. This is true.
Similarly, we would assume that `Left Column:Account A` is 100, equal to its (only) sub-account. However, this is false!

The balance report **should** display this:
```
                   0  Left Column:Account A
                 100    Sub-Account
                   0  Right Column
                -100    Account 1:Sub-Account
                 100    Account 2
--------------------
                   0
```

**Comment by dersuchmann** [comment]
From further testing, I assume there is an error in the function that does the "merging" (i.e. displaying "Left Column:Account A:Sub-Account" in only one line instead of a nested tree view) that **in cases where there is only a single sub-account, merging is done if the parent account amount is zero**. But correct would be **...if the parent account amount is equal to the sub-account**.

I assume this because I tested a modified example:
```
2021/01/01 Test
	Left Column:Account A:Sub-Account    100
	Right Column:Account 1:Sub-Account  -100

2021/01/02 Test
	Left Column:Account A               -0
	Right Column:Account 2               0
```

And here the balance report does **not** do the "merging" for `Left Column:Account A:Sub-Account` (although it should):
```
                 100  Left Column:Account A
                 100    Sub-Account
                -100  Right Column:Account 1:Sub-Account
--------------------
                   0
```

**Comment by zanona** [comment]
@dersuchmann, have you been able to come around your issue by any chance?

Perhaps the debit/credit `--dc ` display mode will help?
I am adding the column titles for readability
```
$ ledger b --dc
         debit         credit        balance  account
           100            100              0  Left Column:Account A
           100              0            100    Sub-Account
           100            100              0  Right Column
             0            100           -100    Account 1:Sub-Account
           100              0            100    Account 2
--------------------------------------------
           200            200              0

```
