### ISSUE TITLE
Regex query string is not evaluated on Termux

### ISSUE THREAD

**Issue by hieu-van** [ledger/ledger#2014]
Hi there, I'm using Ledger 3.2.1-20200518 on Termux 0.108. I'm not able to use regular expression in query string, unlike on Linux. Is this a bug?

**Comment by tbm** [comment]
It's probably your shell interpreting some characters.  Try putting the argument into quotes, e.g. like this:

```
ledger -f books.ledger reg -l "payee =~ /foo/"
```

**Comment by hieu-van** [comment]
> It's probably your shell interpreting some characters. Try putting the argument into quotes, e.g. like this:
> 
> ```
> ledger -f books.ledger reg -l "payee =~ /foo/"
> ```

I tried adding quotes but it didn't work (both double and single quotes). The problem persists in REPL, even with quotes.

**Comment by tbm** [comment]
Can you show the query you're trying?

Does it work without termux?

**Comment by hieu-van** [comment]
Nevermind, I solved it myself. It was due to the shell interpreting an Unicode character as two characters, thus I have to use 2 dots in regex, not one.
