### ISSUE TITLE
Harmony One - support for Ledger Nano X

### ISSUE THREAD

**Issue by emx0r** [ledger/ledger#2026]
Hello,

Harmony One app is currently supported only on Ledger Nano S.
Devs from Harmony One said the code for X support has been already passed to Ledger.

What is the ETA to get the app released?

thanks

**Comment by peterkeen** [comment]
Pretty sure this is the wrong email list for that.

**Comment by tbm** [comment]
This is the repo for the ledger bookkeeping tool.  You want https://github.com/LedgerHQ
