### ISSUE TITLE
Header guards cause undefined behaviour

### ISSUE THREAD

**Issue by jwakely** [ledger/ledger#2049]
Macro names like [`_UTILS_H`](https://github.com/ledger/ledger/blob/460a5661ac20789aa578dc9fb20f3a1ed47e5699/src/utils.h#L44) cause undefined behaviour, because that is a [reserved name](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier).

`UTILS_H` would be a perfectly fine macro name, or `LEDGER_UTILS_H` or `LEDGER_UTILS_H_INCLUDED`, or ...

**Comment by tbm** [comment]
@jwakely can you submit a PR please.

Ideally this should be done for all names/files, not just `_UTILS_H`/`value.h` to keep things consistent.

**Comment by jwakely** [comment]
I'm very unlikely to have time to submit a PR for it myself, sorry.
