### ISSUE TITLE
some code specific to UTF-8 actually accomplishes nothing

### ISSUE THREAD

**Issue by kanreki** [ledger/ledger#2061]
There's some code in `commodity_t::parse_symbol(std::istream&, string&)` (src/commodity.cc) for doing something special with non-ASCII UTF-8 characters. However, it doesn't seem to actually make any difference: it copies bytes into a buffer; but all bytes (except "`invalid_chars`") get copied into the buffer anyway. So this special code seems to be pointless.

Is there some subtlety I'm missing? If not, we might as well excise this useless code.

**Comment by tbm** [comment]
@kcwu since you did some work on UTF-8, maybe you can comment on this ticket.

**Comment by kcwu** [comment]
I guess the code was written that way because the author thought the middle bytes inside UTF-8 may be `invalid_chars`, so he have to parse UTF-8 in order to skip bytes of UTF-8.

However, according to the definition of UTF-8, the intra bytes are always larger than 128, which are not overlapped with `invalid_chars`. Thus, I agree with @kanreki that this function is unnecessary complicated.

**Comment by kanreki** [comment]
The other idea that occurred to me: it looks as if maybe the intention was to avoid copying a partial multi-byte character in the case where the buffer is just about to fill up. Notice how we keep testing the size of the remaining space in the buffer. And if we don't have enough space, the `bytes` variable doesn't get set. But if that was the intention, then of course we should break out of the loop; instead we just fall through to the last branch of the chain of `if` tests.

**Comment by kanreki** [comment]
(A possibly useful regression test file, depending upon if/how we decide to resolve this.)

[testdata.txt](https://github.com/ledger/ledger/files/8337360/testdata.txt)

**Comment by tbm** [comment]
@jwiegley can you comment on this since you probably wrote that code?

@kanreki if John doesn't respond (he's busy), can you submit a pull request with some test cases.

**Comment by kanreki** [comment]
My comment from a moment ago might be a little confusing, because that test file might not actually be a sensible regression test if we do decide to remove that code. Rather, I found it useful in *exploring* whether the code was indeed having any effect.

I'll be quite happy to add a test case or two.

**Comment by jwiegley** [comment]
I think that UTF-8 code was copy/pasted in from some public domain code I found on the web. No objections to removing needless operations.

**Comment by kanreki** [comment]
Great. I'll do that then. Thanks, John.
