### ISSUE TITLE
questions about api

### ISSUE THREAD

**Issue by junsik-kim0** [ledger/ledger#2070]
Hello
I am looking for a bug in ledger using fuzzer
This is the plan to be reported to you.

However, there are questions
Do you know the ledger API list or document?
I really want to make sure that the bugs I found are triggered outside.
BR

**Comment by tbm** [comment]
ledger is a command-line application.  The commands are documented in the man page and the manual.

There's also a Python interface; some documentation is in the source code.

Is this what you're looking for exactly?  I'm not sure I fully understand your question.

**Comment by tbm** [comment]
@junsik-kim0 can you please clarify your question.

**Comment by zanona** [comment]
vote for closing as inactive

**Comment by tbm** [comment]
closing as no reply from reporter.  @junsik-kim0 feel free to comment here or open a new ticket.
