### ISSUE TITLE
Ledger displays unsupported token's address instead of destination address

### ISSUE THREAD

**Issue by sdherr** [ledger/ledger#2073]
I'm using the new Nano S firmware 2.1.0.

I'm attempting to send a non-supported Token using Metamask (version 10.7.1), however the "address" displayed on the Ledger when it's asking me to sign the transaction is actually the *token identity address* not the *destination address*. This feels very wrong to me. The destination address is listed and correct if I enable Debug Data, but the final screen before sending is still showing the token ID address and I don't want to risk sending my tokens there. Is this a bug?

**Comment by tbm** [comment]
This repository is for ledger the command-line bookkeeping tool, not for ledger the crypto wallet.

You want to go here:

https://github.com/LedgerHQ

**Comment by sdherr** [comment]
Ah, how embarrassing. Thank you for your help.

**Comment by tbm** [comment]
You're not the first one to make this mistake ;)
