### ISSUE TITLE
Ledger does not resolve to street value in alias

### ISSUE THREAD

**Issue by gopar** [ledger/ledger#2076]
For some reason, when calling ledger via an alias, the street value is not resolved.
See the prompts below (specifically the 3rd one)

I have `LEDGER_PRICE_DB` set to `data/price_db.dat`
The comand `ledger` is an alias to `/usr/local/bin/ledger --no-color --no-pager --strict $*`

```
$ ledger bal Liabilities:Tithe --price-db data/price_db.dat -V
               $5.97  Liabilities:Tithes
$ ledger bal Liabilities:Tithe -V
               $5.97  Liabilities:Tithes
$ tithe -V
              597 AP  Liabilities:Tithes
$ which tithe
tithe is an alias, defined as "ledger bal Liabilities:Tithe"
$ ledger --version
Ledger 3.2.1-20200518, the command-line accounting tool

Copyright (c) 2003-2019, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.
$
```

I'm not sure what i'm doing wrong (Just started using ledger. Maybe i'm overlooking something)

**Comment by gopar** [comment]
Oh, looks like it might be my environment that is mest up.
I did the following and it works?

```
$ delme
               $5.97  Liabilities:Tithes
$ which delme
delme is an alias, defined as "ledger bal Liabilities:Tithe -V"
$ 
```

I guess as a workaround I'll update my alias to include the `-V` flag

**Comment by tbm** [comment]
"street value" has no predefined meaning in ledger so you'd have to give an example of what's going on.

But this looks like a user error to me.
