### ISSUE TITLE
docs: how to query quoted commodities

### ISSUE THREAD

**Issue by yashovardhan99** [ledger/ledger#2077]
I had a few commodities named `ABC-DEF` which seemed to have issues working with ledger. I am writing this here as I couldn't find any documentation for acceptable characters in a commodity name.

Sample transactions:-
```
2021/10/07 * Purchase
    Assets:Investments'        12 "ABC-Fund" @ $8
    Assets:Savings

2021/11/09 * Purchase
    Assets:Investments         10 "ABC-Fund" @ $10
    Assets:Savings

2021/12/08 * Purchase
    Assets:Investments         20 "ABC-Fund" @ $15
    Assets:Savings
```

Normally ledger works fine but some operations like `--limit` seem to have an issue.

For example, `ledger reg -l 'commodity == "ABC-Fund"'` should output 3 postings but has no output.

I have verified that using an `_` (underscore) instead of a hyphen fixes this. i.e. changing the name from `ABC-Fund` to `ABC_Fund` gives the following outputs:-

```sh
ledger reg -l 'commodity == "ABC_Fund"'
07-Oct-2021 Purchase                        Assets:Investments                          12 ABC_Fund        12 ABC_Fund
09-Nov-2021 Purchase                        Assets:Investments                          10 ABC_Fund        22 ABC_Fund
08-Dec-2021 Purchase                        Assets:Investments                          20 ABC_Fund        42 ABC_Fund
```

**Comment by tbm** [comment]
In your query, the `"` quotation mark is used to quote the string.  But
since it's a quoted commodity, you also need to specify the quotes for
the commodity.  Therefore, you need two quotation marks, like this:

```
ledger -f d reg -l 'commodity == "\"ABC-Fund\""'
```

Maybe someone can add such an example to the docs.

**Comment by yashovardhan99** [comment]
Thanks this seems to work

**Comment by zanona** [comment]
vote for closing as resolved

**Comment by tbm** [comment]
this is not resolved.  It's a common question and should be mentioned in the docs.

**Comment by zanona** [comment]
Sorry, I didn't pay attention to the label.
Would you accept a PR for adding this to the docs?
Also, do you believe this issue could be linked to this https://github.com/ledger/ledger/issues/2010 or that could be a different issue?

**Comment by tbm** [comment]
> Would you accept a PR for adding this to the docs?

Yes, that'd be great.

> Also, do you believe this issue could be linked to this https://github.com/ledger/ledger/issues/2010 or that could be a different issue?

I think it's a different issue but both are related to quoted commodities.
