### ISSUE TITLE
ledger stats error with automated transactions

### ISSUE THREAD

**Issue by yashovardhan99** [ledger/ledger#2079]
I have a couple of automated transactions (similar to those shown in docs) for calculating asset allocations and donations. When running `ledger stats` with those files included, I get the following error:-
```
Error: Assertion failed in "[redacted]/ledger/src/post.cc", line 109:virtual ledger::date_t ledger::post_t::primary_date() const: xact
```
Excluding both the files with automated transactions solves this error and shows the correct output.

This is one of the transactions which is causing the issue:-
```
= /^(?:Income:|Expenses:(?:Bills|Rent|Taxes))/
  (Liabilities:Donations)            (amount * 0.1)
```
This was taken with slight modifications straight from the [docs here](https://www.ledger-cli.org/3.0/doc/ledger3.html#Concrete-Example-of-Automated-Transactions).
I am using Ledger 3.2.1-20200518

**Comment by jwiegley** [comment]
Do you have a fuller example? I tried adding your automated transaction to my own Ledger file, but it passes cleanly.

**Comment by jman223** [comment]
Per Martin's request, I'm adding my test case from the [Stats Report Failure](https://groups.google.com/g/ledger-cli/c/x0miNyyrBxo) Google Groups thread.

**Alias**

`l='ledger -f register.ldg'`

**register.ldg**
_Pared down version of register.ldg used for testing_
```
= /^Income:(?!^Employer|^Federal|^PTO|^Unrealized)/
        (Liabilities:Tithe)                   0.10

include budget.ldg
include register_2022.ldg
include register_2023.ldg
```

**budget.ldg**
_Pared down version of budget file used for testing_
```
~ Monthly
        Expenses:Automobile:Car Wash                             $240.00
        Expenses:Automobile:Gas                                  $400.00
        Assets

~ Monthly
        Income:Interest:Bank Interest                           -$960.00
        Income:Interest:xxxxx Interest                        -$5,298.00
        Income:Interest:xxxxx Interest                       -$11,964.00
        Equity

~ Yearly
        Expenses:Automobile:Registration                         $200.00
        Expenses:Services:Disney Plus                             $75.76
        Expenses:Services:Domains                                $360.00
        Expenses:Services:Dropbox                                $127.79
        Assets
```

**Command**

`l stats`

**Result**

`Error: Assertion failed in "/usr/src/debug/ledger/ledger-3.2.1/src/post.cc", line 109:virtual ledger::date_t ledger::post_t::primary_date() const: xact`

**Notes**
If I comment out the automatic calculation, the stats command runs as expected.

I did some additional testing and found that restoring the automatic calculation and commenting out the budget include also allows the stats command to run as expected.

**Comment by tbm** [comment]
Thanks @jman223 .  Here's a reduced test case that triggers the issue for me:

```
= /^Income:/
    (Liabilities:Tithe)                   0.10

~ Monthly
    Income:Interest:Bank Interest     -$960.00
    Equity
```

**Comment by jwiegley** [comment]
Looks like postings can legitimately have no date at all, and this needed to be accounted for. For the sake of `stats`, we can only really assume the current date in these cases, I think.
