### ISSUE TITLE
Eliding amounts in a transaction with an automated posting

### ISSUE THREAD

**Issue by matthuszagh** [ledger/ledger#2080]
I'd like to add an automated posting to a transaction and also elide the amount from the final posting. I know the manual clearly states this is something you cannot do:

> One thing you cannot do, however, is elide amounts in an automated transaction.

However, this seems like useful functionality. For example, I share a credit card with another individual, which we split 50-50. It would be nice to be able to do something like:

```
= Liabilities:Credit:Shared
    Assets:Reimbursements:Someone  -0.5

2021/10/10 Some Transaction
    Liabilities:Credit:Shared  $-100.00
    Expenses:Some:Category
```

and have the automated posting get the value of $50.00 and the final posting assume the remainder (also $50.00).

Was this capability prevented deliberately, or is it simply incompatible with ledger's internal implementation? If it's deliberate, why was this done?

Is there a different way to accomplish this? I'd like to avoid manually calculating half the value if possible.

**Comment by tbm** [comment]
I can't comment on the fundamental question you're asking.

But you can solve your problem like this:

```
= /^Expenses:/ and expr 'any(account =~ /Liabilities:Credit:Shared/)'
    Assets:Reimbursements:Someone   0.5
    $account                       -0.5

2021/10/10 Some Transaction
    Liabilities:Credit:Shared  $-100.00
    Expenses:Some:Category
```

**Comment by matthuszagh** [comment]
@tbm thank you! That's exactly what I wanted. Sounds like I need to take a closer look at expressions.

Closing this issue as that resolves my problem (and is maybe a hint that eliding an amount in an automated transaction doesn't provide functionality that can't be accomplished through other means). If someone else feels this functionality is needed we can reopen.
