### ISSUE TITLE
ledger as a static library

### ISSUE THREAD

**Issue by dirkarnez** [ledger/ledger#2081]
May I ask is it possible to do this? Knowing that there is shared library build support, but static would also be great! Thank you!

**Comment by kunhtkun** [comment]
Hi!

Could you give a use case for that? Ledger is primarily a command-line application so a static library, which cannot be used by either `ledger` or the Python binding, probably is not useful for most users.

Thanks!

**Comment by dirkarnez** [comment]
@kunhtkun Would like to embed / wrap `ledger` making it usable say in web application.

Thanks!

**Comment by afh** [comment]
Yes, that is possible, @dirkarnez!

Just remove the `SHARED` keyword from the <code>add_library(libledger <del>SHARED</del> ${LEDGER_SOURCES})</code> instruction in [`src/CMakeLists.txt`](https://github.com/ledger/ledger/blob/master/src/CMakeLists.txt#L282) and build ledger as usual; `libledger.a` is then build instead of `libledger.so` (or `libledger.dylib` on macOS):

```
% ar t result/lib/libledger.a | head
__.SYMDEF
stats.cc.o
generate.cc.o
csv.cc.o
convert.cc.o
draft.cc.o
emacs.cc.o
ptree.cc.o
print.cc.o
output.cc.o
```

Do share a link or other information on what you build! 🙂

**Comment by dirkarnez** [comment]
Thank you 🙌🙌🙌 [afh](https://github.com/afh)

**Comment by dirkarnez** [comment]
> Yes, that is possible, @dirkarnez!
> 
> Just remove the `SHARED` keyword from the `add_library(libledger ~SHARED~ ${LEDGER_SOURCES})` instruction in [`src/CMakeLists.txt`](https://github.com/ledger/ledger/blob/master/src/CMakeLists.txt#L282) and build ledger as usual; `libledger.a` is then build instead of `libledger.so` (or `libledger.dylib` on macOS):
> 
> ```
> % ar t result/lib/libledger.a | head
> __.SYMDEF
> stats.cc.o
> generate.cc.o
> csv.cc.o
> convert.cc.o
> draft.cc.o
> emacs.cc.o
> ptree.cc.o
> print.cc.o
> output.cc.o
> ```
> 
> Do share a link or other information on what you build! 🙂

Just successfully produced windows binary v3.3.2 https://github.com/dirkarnez/ledger-prebuilt in my own github workflow, cli with both static and shared library, hopefully to be merged in official github workflow, thx!
