### ISSUE TITLE
"apk add ledger" on alpine throws "ledger (no such package)" since Dec. 20, 2021

### ISSUE THREAD

**Issue by alberto56** [ledger/ledger#2091]
I maintain the Docker version of ledger which is at https://hub.docker.com/r/dcycle/ledger and whose code is at https://github.com/dcycle/docker-ledger and referenced in [Ledger's README](https://github.com/ledger/ledger/blame/474d2b8d091ba865c17c554a4ecdfb0d05325d3f/README.md#L41-L46).

I have a Jenkins job which attempts to rebuild the image weekly with the latest version of Ledger on Alpine.

The job ran successfully on Dec. 13, 2021, however since Dec. 20, 2020, I am getting the following error:

```
 > [3/3] RUN apk add ledger:                                                                                            
#6 0.364 ERROR: unable to select packages:                                                                              
#6 0.364   ledger (no such package):                                                                                    
#6 0.385     required by: world[ledger]                                                                                 

```

[My code](https://github.com/dcycle/docker-ledger/blob/master/Dockerfile) is based on https://gitlab.com/alensiljak/ledger-docker-alpine/-/blob/master/Dockerfile

What would be the next step in debugging this and making sure the builds can resume?

**Comment by alberto56** [comment]
You can see the result of the test script at https://app.circleci.com/pipelines/github/dcycle/docker-ledger/28/workflows/cf2d22c0-455a-4c8c-a723-5ea14e0d67f8/jobs/30

**Comment by MisterY** [comment]
Hi,  Alberto! Have you resolved this? Ledger seems to be available in the repos:

https://pkgs.alpinelinux.org/packages?name=ledger&branch=edge

I would assume it is a matter of including the right repository in the config. I'll have a more detailed look if this is still an issue.

**Comment by MisterY** [comment]
It is now in the community repository while before it was in testing, if memory serves me well.

**Comment by alberto56** [comment]
Hi! That works!

There were two issues:

* it seems that the package is on Alpine version "edge" but not alpine version "3", I therefore needed to base my image on alpine:edge, not alpine:3
* I used the "community", not "testing" repository as you suggested. 

Thanks! Closing this issue.

**Comment by MisterY** [comment]
Great!
