### ISSUE TITLE
Show actual message to sign, not the hash of the message

### ISSUE THREAD

**Issue by maaft** [ledger/ledger#2124]
Signing messages (e.g. through metamask) is very common nowadays for gasless transactions.

However,  the ledger wallet does not currently show the actual message that the user is going to sign.

This is a **huge security vulnerability** IMHO.

Currently, any MITM-attacker could just intercept the message sent to ledger, changing the message to a malicious one in the process.
The user would not notice the attack unless he manually compares the hash shown on his device and the sha256 hash of the message displayed in metamask.

**Comment by tbm** [comment]
This repository is for ledger-cli, an accounting software, and not for ledger, the crypto wallet.

You may want to report your issue here:

https://github.com/LedgerHQ
