### ISSUE TITLE
Ledger Manual Update - 2.2.3 Cleared Report

### ISSUE THREAD

**Issue by jman223** [ledger/ledger#2125]
The command example for the "Cleared Report" in section 2.2.3 reads 

`ledger -f drewr3.dat cleared`

but should read 

`ledger -f drewr3.dat --cleared`

**Comment by tbm** [comment]
The example is correct.

`cleared` is a command which shows a cleared report

`--cleared` is an option that limits output to cleared transactions; this can be used in combination with e.g. `reg`

**Comment by afh** [comment]
Closing as works as intendend.
