### ISSUE TITLE
Rename default branch from `master` to `main`?

### ISSUE THREAD

**Issue by afh** [ledger/ledger#2127]
Many projects using [git](https://git-scm.com) have renamed the default branch from `master` to `main` (see [Regarding Git and Branch Naming](https://sfconservancy.org/news/2020/jun/23/gitbranchname/), [`github/renaming`](https://github.com/github/renaming)) and [git version 2.28.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.28.0.txt#L107-L110) introduced the `init.defaultBranch` option to configure the name for the default branch when creating a new git repository.

[Searching for `master` in this repositry](https://github.com/ledger/ledger/search?q=master) ~280 results are found, many are unrelated to the git master branch.

At first glance it seems the following files would need to be updated alongside a renaming:

* [`README.md`](README.md)
* [`CONTRIBUTING.md`](CONTRIBUTING.md)
* [`appveyor.yml`](appveyor.yml)
* [`.github/workflows/cmake.yml`](.github/workflows/cmake.yml)
* [`tools/push`](tools/push)

**Some open questions:**
* What other systems would need to be updated?
* Would it make sense to make the same change in this org's main (pinned?) repos: [ledger](https://github.com/ledger/ledger), [ledger-mode](https://github.com/ledger/ledger-mode), [ledger-website](https://github.com/ledger/ledger-website), [vim-ledger](https://github.com/ledger/vim-ledger)?
* What are your thoughts?

**Comment by afh** [comment]
@jwiegley and @tbm what are your thoughts on this?

**Comment by tbm** [comment]
I'm generally in favour of this.

I would, however, keep a `master` branch around and sync `main` to it periodically (at least for a while, to make the transition easier).

ledger-mode and vim-ledger have separate maintainers so we'd have to coordinate with them.  CC @purcell @alerque

**Comment by alerque** [comment]
The maintainers of this repository are obviously welcome to make their own choices, but in general I am not in favor of these renames. Just because many folks subscribe to CRT ideas and some others go along for the ride doesn't mean everybody has to agree with their interpretation of the language issues involved. I do not and in general plan on leaving the repositories I directly maintain the way they are.

**Comment by purcell** [comment]
As a maintainer, I would broadly prefer `main` to `master`, and I use the former as a default. However, this repository has been in the wild for a long time, and it'll take legwork from us _and_ unwitting downstream maintainers to fix up things that will invitably break as a result of this, so my personal preference would be to leave things as-is. I'd like to think people understand that not changing a long-standing (if outdated) default for an old project is not a statement of ideals. Just my 2c: happy for other maintainers to chime in.

**Comment by jwiegley** [comment]
I have no strong sentiments here, since I use both in various repositories, so whatever we choose I'll just change my scripting and muscle memory to match. If the contributors prefer `main`, let's migrate over to `main` per @tbm 's suggestion.

**Comment by alerque** [comment]
✘ Nay

Also:

1. I think you're over complicating this. Just let whoever handles release cycle management make a judgement call based on discussion and move on.

2. If any maintainer does choose to go that route, **do not keep a synchronized branch under the old name**. I have to  That makes it worse not better. There are quite a few reasons for this including GitHub tooling that facilitates the MOVE that gets clobbered if you keep the old branch. The people that would be spared the momentary pain of updating their hard coded configs will only be delayed, and in the mean time subject to other issues. That's not even to mention the chaos of PR targets which can't be changed without closing and reopening. Seriously don't do this.

3. If anyone is a maintainer and doesn't feel this change is right for their repo then please stop pressuring them.

**Comment by afh** [comment]
**✔︎ Aye**

Thanks for you comments, @alerque. 2. is good to know.

My kind request for reconsideration if the ayes have it was meant as just that, if the words came across as pressuring then they were misunderstoot or ill-chosen by me. Your **✘ Nay** is heard loud and clear.

**Comment by purcell** [comment]
I'm a **✘ Nay** per my previous comment. Also agree re. it being better to not run with synchronised branches to paper over any downstream breakage.

**Comment by afh** [comment]
It seems there are two Nays and two Ayes (counting @tbm's being _"generally in favour of this"_ as an Aye). Given that @jwiegley _"[has] no strong sentiments here"_  and is less effort to keep things are they are I'm going to close this out.

Thanks everyone for taking the time and chiming in. :+1:
