### ISSUE TITLE
Balance assignment does not (but should) update display precision

### ISSUE THREAD

**Issue by shth** [ledger/ledger#2129]
# Env
- macOS Big Sur 11.5.2
```
$ ledger --version
Ledger 3.2.1-20200518, the command-line accounting tool
```
# Description
I am trying to automatically track the interests received from my broker account, with balance assignment. Here's an example of what I did.

```
2022/08/04 * Stock interest
    Assets:Broker  = 1.1 AAPL
    Income:Stock Interests

2022/08/03 * Bought stock
    Assets:Broker  1 AAPL
    Equity:Stock
```

The result is this. From my understanding, the `= 1.1 AAPL` assignment should make the `Assets:Broker` posting cost equal `0.1 AAPL`, therefore `Income:Stock Interests` should be automatically balanced to `-0.1 AAPL`? 

Have I misunderstood something or is this a bug?
```
:             2.1 AAPL  Assets:Broker
:              -1 AAPL  Equity:Stock
:              -1 AAPL  Income:Stock Interests
: --------------------
:                    0
```

I read that there are some[ issues](https://github.com/ledger/ledger/issues/1092) with the parse order of balance assignment. So I tried to do this

```
2022/08/03 * Bought stock
    Assets:Broker  1 AAPL
    Equity:Stock

2022/08/04 * Bought stock
    Assets:Broker  = 1.1 AAPL
    Income:Stock Interests
```

but the result is this
```
:               1 AAPL  Assets:Broker
:              -1 AAPL  Equity:Stock
: --------------------
:                    0
```

Thanks in advance!

**Comment by tbm** [comment]
Yes, as you found out transactions are processed in the order of the file, not order per date.  So you need to re-order them.

The second example works correctly.

So why do you not get the result you want?  Ledger uses the precision from your file to work out the display precision.  In your example you say "1 AAPL", so it doesn't use decimals for AAPL.  So while the value is 1.1 it will show 1 because of this.

You can see this here:

```
ledger -f a reg :br
2022-08-03 Bought stock                              Assets:Brokerage                                                  1 AAPL                   1 AAPL
2022-08-04 Bought stock                              Assets:Brokerage                                                0.1 AAPL                   1 AAPL
```

There are 2 solutions:

1) Add this line

```
D 1000.00 AAPL
```

This tells ledger to use more precision for the display.

2) Change

```
2022/08/03 * Bought stock
    Assets:Brokerage  1 AAPL
```

to

```
2022/08/03 * Bought stock
    Assets:Brokerage  1.00 AAPL
```
which again tells ledger to use more precision.

If you do one of these, you'll see:

```
           1.10 AAPL  Assets:Brokerage
```

**Comment by tbm** [comment]
Actually, I think I'll re-open this issue because:

```
2022/08/04 * Bought stock
    Assets:Broker  = 1.1 AAPL
```

imho the `= 1.1 AAPL` balance assignment should affect the display precision, but doesn't appear to.

**Comment by shth** [comment]
@tbm Thanks for the quick response. It works as you described.

Btw just asking will the parse order instead of date order issue be fixed? Because I think it is more convenient to add new transactions from the top, but this issue kind of blocks that.

**Comment by tbm** [comment]
I don't know if it will be fixed in the future, but certainly not soon as nobody is working on it and from what I understand it's not so easy to fix.

**Comment by shth** [comment]
Understandable. Though what do you think if some pre-processors were to be added, so that the input files are sorted by dates before passing to the parser?

**Comment by tbm** [comment]
Please discuss the sorting issue in the relevant ticket.  This ticket is only about display precision issue.  Ledger development isn't very active but I'm sure contributions in this area would be accepted. (But please discuss in the relevant ticket)

**Comment by shth** [comment]
Got it. Thanks!
