### ISSUE TITLE
Bug in handling utf-8

### ISSUE THREAD

**Issue by horasio** [ledger/ledger#2132]
In latest commits from July 20:

Local config : MacOS 12.6 Monterey, Terminal in UTF8.
I guess the fix above is not enough because the July 19 commit works well with the Euro symbol as a commodity :
Python 3.7.14 (default, Sep 10 2022, 11:16:56)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

```
import ledger
a=ledger.Amount('€1.3')
a
€1.3
```
But with this commit, it's all buggy :

```
ledger.Amount('€1.3')
ﾬ 1
```

See how my Euro symbol has become a Korean syllable!

**Comment by afh** [comment]
A PR (#2133) addressing this regression is now available, @horasio. Any testing you could do and feedback you could give is greatly appreciated :pray:

**Comment by horasio** [comment]
All good as far as my tiny test goes. See my comment in your PR. Thank you!
