### ISSUE TITLE
--prefix is ignored when building from master branch

### ISSUE THREAD

**Issue by lawlist** [ledger/ledger#2141]
I'm running Debian 8.11.1 in a VirtualBox machine on a MacPro 4,9 desktop with OSX 10.6.8.   When building from the master branch cloned today (11/06/2022), the --prefix is ignored and the executables are installed into the root directory of the cloned repository.   The following is the configure command line that I am using, with the cloned master branch being  downloaded to /tmp and existing at /tmp/ledger

{{{
sudo PATH=$PATH:/opt/cmake-3.24.3-linux-x86_64/bin ./acprep update --prefix=/opt/ledger
}}}

I would like to install the ledger family of executables into /opt/ledger

**Comment by adamipc** [comment]
I had a similar problem and just did an `./acprep gitclean` and rebuilt which fixed it.

**Comment by lawlist** [comment]
I tried again this evening with a brand new clone and the build succeeds, but the destination prefix is disregarded.  Maybe there is a `make install`, or the equivalent thereof, that I'm missing?

PATH=$PATH:/opt/cmake-3.24.3-linux-x86_64/bin ./acprep update --prefix=/tmp/test

**Comment by lawlist** [comment]
It turns out that I simply did not use `make install`.  This was my first experience using cmake and an acprep configuration utility.  I'll make a note to my file that this requires `make install` like what I'm use to seeing with other unrelated installations.
