### ISSUE TITLE
docs: merge aux date and effective date sections

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#2150]
@simonmichael commented on IRC:

```
00:31 < sm> https://www.ledger-cli.org/3.0/doc/ledger3.html#Auxiliary-dates and 
00:31 < sm> https://www.ledger-cli.org/3.0/doc/ledger3.html#Effective-Dates are documenting the same thing I think
```

they are the same, yeah...

**Comment by afh** [comment]
After a quick read I see value in keeping them separate as section **5.3 Auxiliary dates** succinctly introduces auxiliary/effective dates in the context of transactions while section **5.22.7 Effective Dates** goes into more detail about auxiliary/effective dates in the context of automated transactions and what can be achieved with them.

The way that I'd improve this—happy to draw up a PR, if you agree—is by making the relation between auxiliary and effective date, i.e. one is just an alias for the other, explicit and cross reference the sections.

What are your thoughts on this @tbm?

**Comment by tbm** [comment]
You have looked at it in more detail, so whatever you think is best works for me.

**Comment by afh** [comment]
Sounds good, @tbm. I've put up #2188 for review…
