### ISSUE TITLE
boost patches

### ISSUE THREAD

**Issue by spaette** [ledger/ledger#2162]
The Slackware Community (SlackBuilds.org) has these patches for ledger-3.2.1.tar.gz.

The first one doesn't appear to have any effect on the build; the second might be considered for merge with upstream.

CMakeLists.txt.patch

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 15cb7ef90..bb8bfa2dc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -12,7 +12,7 @@ set(Ledger_TEST_TIMEZONE "America/Chicago")

 # Point CMake at any custom modules we may ship
 list(APPEND CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake")
-if(${CMAKE_VERSION} VERSION_LESS "3.16.0")
+if ((${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.7.0") AND (${CMAKE_VERSION} VERSION_LESS "3.16.0"))
   # use backported module from 3.15 (introduced 3.12) to support older versions of cmake
   list(APPEND CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake/python-backport")
 endif()
```

boost-176.patch

```patch
diff --git a/src/expr.cc b/src/expr.cc
index c8945d3..ad2589a 100644
--- a/src/expr.cc
+++ b/src/expr.cc
@@ -278,7 +278,7 @@ value_t expr_value(expr_t::ptr_op_t op)
 value_t source_command(call_scope_t& args)
 {
   std::istream * in = NULL;
-  scoped_ptr<ifstream> stream;
+  std::unique_ptr<ifstream> stream;
   string pathname;
 
   if (args.has(0)) {
diff --git a/src/format.h b/src/format.h
index 15431cf..57f3650 100644
--- a/src/format.h
+++ b/src/format.h
@@ -65,7 +65,7 @@ class format_t : public expr_base_t<string>, public noncopyable
     std::size_t                  min_width;
     std::size_t                  max_width;
     variant<string, expr_t>      data;
-    scoped_ptr<struct element_t> next;
+    std::unique_ptr<struct element_t> next;
 
     element_t() throw()
       : supports_flags<>(), type(STRING), min_width(0), max_width(0) {
@@ -103,7 +103,7 @@ class format_t : public expr_base_t<string>, public noncopyable
     void dump(std::ostream& out) const;
   };
 
-  scoped_ptr<element_t> elements;
+  std::unique_ptr<element_t> elements;
 
 public:
   static enum elision_style_t {
```

There are messages output during build.

```
The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use
<boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain
the current behavior.
```

Owing to deprecation  better to implement the messages' first suggestion.

FWIW, the messages' second suggestion could be implemented as follows.

system.hh.in

```diff
  #define HAVE_BOOST_159_ISSUE_39  @HAVE_BOOST_159_ISSUE_39@
+ #define BOOST_BIND_GLOBAL_PLACEHOLDERS        0

  #define DEBUG_MODE               @DEBUG_MODE@
```

**Comment by afh** [comment]
From a first glance the changes in the patch look like they could break compatibility with previous version of boost.
* Can we ensure that applying the patches maintains "compilability" 😬 with the currently Ledger required minimum boost version, i.e. 1.49.0
* Or increase the required minimum boost version to a version that allows the patches to applied and allows Ledger to be compiled on a wide range of systems?

**Comment by tbm** [comment]
1.49.0 appears to be from 2012 so I think there'd be little resistance in pumping the requirement (but to where exactly).

**Comment by afh** [comment]
@spaette do you have any information on which version of boost introduced changes that make the patch proposed in this PR necessary?

@tbm knowing that might be a good starting point for a conversation and decision which version to bump to.

**Comment by spaette** [comment]
> Do you know who the author of `boost-176.patch` is?

The Slackware Community maintainer of the package cites alpinelinux.

https://git.alpinelinux.org/aports/tree/community/ledger

**Comment by spaette** [comment]
> currently Ledger required minimum boost version

Is that solely appearing in CMakeLists.txt and README.md?

Noted is that acprep appears to include `    boost_major   = `.

**Comment by afh** [comment]
[Boost 1.65.0](https://www.boost.org/users/history/version_1_65_0.html) was released August 21st **2017** that's more than 5 years ago. I feel most distros have updated to this or a newer version. Here's the result from a quick research about some distros and the version of boost they offer. Maybe folks could chime in with other distros they can think…

| Distro | Boost Version |
|---|---|
| ✅ OpenBSD >=6.6 | [1.66–1.80](http://ftp.openbsd.org/pub/OpenBSD/7.2/packages/amd64/)|
| ✅ alpine 3.17.1|[1.80](https://pkgs.alpinelinux.org/packages?name=*boost1.8*&branch=v3.17&repo=&arch=&maintainer=) |
| ✅ debian bullseye stable | [1.74](https://packages.debian.org/search?keywords=boost+python&searchon=names&suite=stable&section=all) |
| ✅ debian buster oldstable | [1.67](https://packages.debian.org/search?keywords=boost+python&searchon=names&suite=oldstable&section=all) |
| ✅ ubuntu kinetic|[1.74](https://packages.ubuntu.com/search?keywords=boost-python&searchon=names&suite=kinetic&section=all) |
| ✅ ubuntu jammy|[1.74](https://packages.ubuntu.com/search?keywords=boost-python&searchon=names&suite=jammy&section=all)|
| ✅ ubuntu focal|[1.71 and 1.67](https://packages.ubuntu.com/search?keywords=boost-python&searchon=names&suite=focal&section=all)|
| ✅ ubuntu bionic|[1.65 and 1.62](https://packages.ubuntu.com/search?keywords=boost-python&searchon=names&suite=bionic&section=all)|

**Comment by spaette** [comment]
AFAIK, current RedHat and S.u.S.E. releases offer boost > 1.74.

https://github.com/ledger/ledger/commit/49a0601c142d535afe5bc722593535bf66408b2d

I presume the above patch has outlived it usefullness as of boost 1.60.

**Comment by afh** [comment]
Do I infer correctly that if we update the minimum required version of boost to, let's say 1.62, we would be able to support all major distros and their different versions listed above without this patch?

**Comment by spaette** [comment]
> let's say 1.62

Ubuntu 18.04 LTS (a.k.a. bionic) has had several update releases.

If 18.04's most recent update release is offering boost >= 1.65 then I don't see an impediment to updating  the minimum required version of boost to 1.65, concomitant with reverting the presumed as thereby rendered useless https://github.com/ledger/ledger/commit/49a0601c142d535afe5bc722593535bf66408b2d.

If @c-14's reproduced comment is correct then Ledger upstream already requires boost 1.65.

Furthermore https://github.com/ledger/ledger/commit/69e6b89cf8d2820d28174e7ffaea1c59a0f84d3f appears to have been merged in substitution for the changes in `boost-176.patch`.

So what remains is whether the compile messages should be attended to.

system.hh.in

```diff
+ #define BOOST_BIND_GLOBAL_PLACEHOLDERS        0

  #define DEBUG_MODE               @DEBUG_MODE@
```

**Comment by afh** [comment]
@spaette would you be open to changing this PR (or close it in favor of a new one), so that it updates the minimum required version for boost?

**Comment by spaette** [comment]
> If @c-14's reproduced comment is correct then Ledger upstream already requires boost 1.65.

Evidentally that information was incorrect as the header was present much earlier than boost version 1.65.

```
$ tar -xf boost-1.49.0-x86_64-3.txz
$ ls usr/include/boost/smart_ptr
bad_weak_ptr.hpp             enable_shared_from_this2.hpp  owner_less.hpp    shared_array.hpp
detail                       intrusive_ptr.hpp             scoped_array.hpp  shared_ptr.hpp
enable_shared_from_this.hpp  make_shared.hpp               scoped_ptr.hpp    weak_ptr.hpp
$ 
```

That now being clarified perhaps building with boost 1.62 prior to the next release could be attempted.

With a successful build:

1. the boost version could be bumped to 1.62
2. the thereby rendered useless https://github.com/ledger/ledger/commit/49a0601c142d535afe5bc722593535bf66408b2d could be reverted
3. a decision could be made on whether to attend to the below compile messages

> The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use
<boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to to retain the current behavior.

I'm running boost 1.78 so would be unable to attempt a repo clone build using 1.62.

**Comment by afh** [comment]
I'm using nixpkgs on aarch-darwin and could attempt a repo clone build, unfortunately nixpkgs doesn't provide 1.62, but does provide 1.65 (for a list of available versions in nixpkgs see [`NixOS/nxpkgs/pkgs/development/libraries/boost`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/boost))

**Comment by spaette** [comment]
> decision which version to bump to

Boost 1.65 includes python27 code.

> list of available versions in nixpkgs

Do you want to try repo clone build with 1.70?

**Comment by afh** [comment]
I'd be okay with bumping the minimum boost requirement to [1.70](https://www.boost.org/users/history/version_1_70_0.html), it was released in April 2019. Dropping support for Debian oldstable (Jul 2019–Sep 2020) and OpenBSD <= 6.8 (Oct 2020) isn't great, but I find it worthwhile with the added benefit of ridding Python 2 from Ledger.

ℹ️ I yet to succeed to build Ledger from a repo clone (`0ade3a55` as of this writing) with Boost 1.70 as the `boost_date_time` isn't found by CMake with my nixpkgs setup. Building Ledger from a repo clone and running the tests with Boost 1.72 using nixpkgs did succeed.

**Comment by spaette** [comment]
To be precise python 2 and 3 series code appeared together in several boost releases.
