### ISSUE TITLE
RegressTest_786A3DD0 fails on GitHub Linux CI

### ISSUE THREAD

**Issue by jwiegley** [ledger/ledger#2176]
I've tried running this test on both macOS 12 and Ubuntu 22.04, and it passes on both. I do not know yet why it fails on GitHub's CI.

**Comment by afh** [comment]
I'll have another look tomorrow with a well-rested pair of 👀

Depending on your availability and schedule, @jwiegley, maybe you could have a peek at [the run](https://github.com/ledger/ledger/actions/runs/4058734179/jobs/6986012129) from #2178, hopefully this provides helpful information for finding a solution to the failed GH CI Linux tests.

**Comment by afh** [comment]
Fixed by #2178
