### ISSUE TITLE
`--pedantic` and `--check-payees` with unexpected behavior

### ISSUE THREAD

**Issue by rolfschr** [ledger/ledger#2202]
Hi,

I have been using ledger for roughly a decade. My journal has ~33k lines. I recently switched OS version and initially had ledger 3.2.1 installed after the update. I now updated to Ledger 3.3.0-20230208. I have issues with my journal that I haven't had before. I don't remember the ledger version that I was previously running (must have been a bit older).

In the past, I run ledger like so

```bash
$ type led
led is aliased to `ledger -f main.txt --pedantic --check-payees --price-db prices.txt --market --explicit'
```
(I realize that as of today `--explicit` is not useful anymore. I'll remove it from now on).

My journal is full of entries like this ([download test.txt](https://github.com/ledger/ledger/files/10779833/test.txt)):

```
commodity EUR
account Vermoegen:Girokonto
account Ausgaben:Haushalt:TelefonInternet

2015/10/08 * 1u1 Telecom GmbH
    ; CSV data:
    ; from : "08.10.2015","08.10.2015","LASTSCHRIFT","1u1 Telecom GmbH","KD-Nr. XXXXX","DE97500400000589011600","COBADEFFXXX","-19,99","DE77ZZZ00000569719    ","0200009180224         ","004327988900          ";
    ; (raw): "08.10.2015";"08.10.2015";"LASTSCHRIFT";"1u1 Telecom GmbH";"KD-Nr. XXXXX";"DE97500400000589011600";"COBADEFFXXX";"-19,99";"DE77ZZZ00000569719    ";"0200009180224         ";"004327988900          ";
    Ausgaben:Haushalt:TelefonInternet       19.99EUR
    Vermoegen:Girokonto                -19.99EUR
```

These entries come from a [personalized version](https://github.com/rolfschr/GSWL-ecosystem/blob/master/convert.py#L151) of `ledger convert`.  As of today, I cannot inspect my journal anymore. The following still works:

```
$ ledger -f test.txt -w reg
15-Oct-08 1u1 Telecom GmbH                   Ausgaben:Haushalt:TelefonInternet                   19.99EUR             19.99EUR
                                             Vermoegen:Girokonto                                -19.99EUR                    0
```
Being pedantic doesn't work anymore:
```
$ ledger -f test.txt -w --pedantic reg
While parsing file "/run/mount/veracrypt4/Buchhaltung.git/test.txt", line 10:
Error: Unknown metadata tag '(raw)'
```
The docs say that a (metadata) tag is surrounded by two colons. This doesn't seem to be the case here. I can work around this problem by adapting [my format](https://github.com/rolfschr/GSWL-ecosystem/blob/master/convert.py#L154). Removing the colon will make the command succeed. Note how interestingly, the `from :` line doesn't cause any issue. Removing the parens also makes the command work again. I.e. either `raw: ...` or `(raw) ...` is fine but `(raw): ...` is not.

---

Furthermore, I cannot use `--check-payees` neither anymore:

```bash
$ ledger -f test.txt -w --pedantic --check-payees reg
While parsing file "/run/mount/veracrypt4/Buchhaltung.git/test.txt", line 5:
While parsing transaction:
> 2015/10/08 * 1u1 Telecom GmbH
Error: Unknown payee '1u1 Telecom GmbH'
```
(Succeeds with `--strict` but gives the warning nevertheless). The docs say "A line beginning with a number denotes a transaction.  [...]  The format of the first line is [...] Following these is the payee, or a description of the posting." It seems like I cannot use a "desc" here when using `--check-payees`.  This has definitely worked in the past.

---

For both cases, I'm not sure anything is wrong here. A [bug](https://www.ledger-cli.org/3.0/doc/ledger3.html#Payee-metadata-tag) is mentioned in the docs but I don't know whether this is related. Maybe the behavior is (now) expected and the docs are just misleading. The first issue feels a little bit like a bug to me, though.

I appreciate the software a lot!

**Comment by tbm** [comment]
@rolfschr as far as I can tell, ledger works as expected in your case.

You cited the manual about tags but note that ledger makes 2 distinctions:

* Tags: the syntax is `:foo:`, i.e. as you quote: colon tag colon
* Metadata: the syntax for that is `key value`:

the reason `from :` is not meta-data is because of the space before the colon: if you remove that, you'll also get a warning about that.

the reason `(raw)` is a meta-data key is because brackets are allowed (ledger is very permissive in what it accepts).  Run `ledger tags` and you'll see `(raw)` listed.

So the solution. Add this to your file:

```
tag (raw)
```

However, what I'd do to clean-up things is:

* Remove the space in `from :` and make it meta-data
* Rename `(raw)` to `raw` to give it a better name
* Declare `from` and `raw`.

Then you can use the meta-data and do queries like:

```
ledger reg -l "tag('raw') =~ /1u1 Telecom/)"
```

**Comment by tbm** [comment]
Sorry, I didn't notice your comment about `--check-payees`:

> The docs say "A line beginning with a number denotes a transaction. [...] The format of the first line is [...] Following these is the payee, or a description of the posting." It seems like I cannot use a "desc" here when using --check-payees.

Unfortunately, ledger makes no distinction between payees and descriptions.  So if you use `--check-payees` you either have to make sure only to use payees (e.g. company names) and put the description somewhere else (e.g. some meta-data) or to declare every description with `payee`.
 
> This has definitely worked in the past.

I don't know.  Maybe you had no `payee` declarations.

As far as I can tell, it works as expected, but I agree that the lack of distinction between payee and description makes it fairly useless.

**Comment by rolfschr** [comment]
Hi @tbm,

thanks for the clarifications. The `from`/`raw` lines are not (meta) tags at all. They simply serve as additional information for me. I'll just change the format to `; from ....` and `; raw ...` (i.e. without colons nor parens) and then this should be fine for me. This way, `--pedantic` will work for me again.

As for the `--check-payees`, I am apparently old enough to have seen it working differently:

![image](https://user-images.githubusercontent.com/1188465/221342391-d5a4c221-6ddc-4f24-bf9d-681faa43379a.png)
(I.e. version 3.1.1 still worked the way I was used to it.)

That being said, I'll not use `--check-payees` for now. I appreciate the efforts for this software and I'll close this issue.

**Comment by tbm** [comment]
Can you run `--pedantic --check-payees` with 3.1.1 on the following example. Sorry, I don't have 3.1.1 around.

```
commodity EUR
account Vermoegen:Girokonto
account Ausgaben:Haushalt:TelefonInternet
payee foo

2015/10/08 * 1u1 Telecom GmbH
    Ausgaben:Haushalt:TelefonInternet       19.99EUR
    Vermoegen:Girokonto                -19.99EUR
```

**Comment by afh** [comment]
FYI: @rolfschr A space in front of the colon is enough to make ledger regard the lines as notes opposed to as tags or metadata. Could be that this changes in the future though…

```
commodity EUR
account Vermoegen:Girokonto
account Ausgaben:Haushalt:TelefonInternet

2015/10/08 * 1u1 Telecom GmbH
    ; CSV data:
    ; from : "08.10.2015","08.10.2015","LASTSCHRIFT","1u1 Telecom GmbH","KD-Nr. XXXXX",…
    ; raw  : "08.10.2015";"08.10.2015";"LASTSCHRIFT";"1u1 Telecom GmbH";"KD-Nr. XXXXX";…
    Ausgaben:Haushalt:TelefonInternet       19.99EUR
    Vermoegen:Girokonto                -19.99EUR
```

Also ledger is UTF-8 aware, so if desired you could use `€` as the commodity symbol and Umlauts in Payees, Account Names, etc., e.g. `Vermögen:Girokonto`. Depending on other tools you may use with you data those may have a harder time dealing with non-ASCII.

**Comment by rolfschr** [comment]
> Can you run `--pedantic --check-payees` with 3.1.1 on the following example. Sorry, I don't have 3.1.1 around.
> 
> ```
> commodity EUR
> account Vermoegen:Girokonto
> account Ausgaben:Haushalt:TelefonInternet
> payee foo
> 
> 2015/10/08 * 1u1 Telecom GmbH
>     Ausgaben:Haushalt:TelefonInternet       19.99EUR
>     Vermoegen:Girokonto                -19.99EUR
> ```

![image](https://user-images.githubusercontent.com/1188465/221358016-f591aa5b-2e29-4ef3-8ace-9d2b926748bd.png)

**Comment by tbm** [comment]
* Rolf Schröder ***@***.***> [2023-02-25 04:56]:
> > commodity EUR
> > account Vermoegen:Girokonto
> > account Ausgaben:Haushalt:TelefonInternet
> > payee foo
> > 
> > 2015/10/08 * 1u1 Telecom GmbH
> >     Ausgaben:Haushalt:TelefonInternet       19.99EUR
> >     Vermoegen:Girokonto                -19.99EUR
> 
> ![image](https://user-images.githubusercontent.com/1188465/221358016-f591aa5b-2e29-4ef3-8ace-9d2b926748bd.png)

hmm, maybe it needs `--explicit` too.

I have a theory on why the behaviour changed, but I guess it doesn't
really matter.  The explanation of --check-payees (i.e. ledger not
differentiating between payee and description) is correct.

-- 
Martin Michlmayr
https://www.cyrius.com/
