### ISSUE TITLE
Regression when specifying format for commodity "h"

### ISSUE THREAD

**Issue by Boldewyn** [ledger/ledger#2205]
We’re using `ledger` as time management tool and have added the following lines to allow appropriate German formatting of hours:

```
commodity h
    format 1.000,00 h
    default
```

When upgrading to ledger 3.3.0, running any ledger command results in the error message:

    While parsing file "/time/user.journal", line 722:
    Error: commodity directive symbol h and format directive symbol s should be the same
    
This seems to be the same error as [this one reported on reddit](https://www.reddit.com/r/plaintextaccounting/comments/10xgg4x/comment/j95k8y7/?utm_source=share&utm_medium=web2x&context=3) which allocates the error message in https://github.com/ledger/ledger/blame/master/src/textual.cc#L1137

This is a regression from 3.2.1 and older where the above statement worked perfectly fine.

**Comment by tbm** [comment]
I guess the problem is that `h` is built-in for hours which is somehow treated the same as `s`?

Adding @jwiegley 

So I guess we have to special case this in the case.

A regression introduced in commit 1a70b33b4f8b6f8d4844b1b30dde568ae311d0ac

**Comment by tbm** [comment]
CC @madroach

**Comment by afh** [comment]
ℹ️ Wanted to call out the `--time-colon` option, which changes the time commodity's base from 100 to 60, so that 90 minutes is reported as 1:30 instead of 1,5.

**Comment by jwiegley** [comment]
This won't just affect builtin commodities, but any commodity that supports conversions. The checking code in `1a70b33` needs to ensure that the commodity are related, not just identical, it seems.

**Comment by jwiegley** [comment]
The fix seems simple enough.
