### ISSUE TITLE
ledger manual link broken

### ISSUE THREAD

**Issue by taviso** [ledger/ledger#2211]
The documentation link on ledger-cli.org appears to be broken.

Reproduce:
- Click here https://www.ledger-cli.org/docs.html
- Click "Ledger 3 manual"
- Result, "Access Denied"

I think the link should be https://www.ledger-cli.org/3.0/doc/ledger3.html which still works.

**Comment by afh** [comment]
Thank you for the report, @taviso, we are well aware of the issue and are working on a solution. For details and updates please see [`ledger/ledger-website#46`](https://github.com/ledger/ledger-website/issues/46).

**Comment by afh** [comment]
Forgot to mention that the current WIP is available at https://ledger.github.io. The ledger-cli.org will remain in use and should be the first (and likely only) way ledger users access ledger's website.

**Comment by valankar** [comment]
> Forgot to mention that the current WIP is available at https://ledger.github.io. The ledger-cli.org will remain in use and should be the first (and likely only) way ledger users access ledger's website.

Just a note that this redirects to https://www.ledger-cli.org/ for me, and has the same broken links.

**Comment by afh** [comment]
Thanks for mentioning this, @valankar, I noticed the redirect too and I believe this has to do with the pending DNS validation from the custom domain setting for the GitHub Pages.
Please subscribe to [ledger/ledger-website#46](https://github.com/ledger/ledger-website/issues/46) for updates on the migration.
