### ISSUE TITLE
related transactions dont work with bucket

### ISSUE THREAD

**Issue by taviso** [ledger/ledger#2220]
I think `reg --related` is broken when using `bucket`.

Consider this transaction:

```
2023/01/01 * Payment
    Assets:Checking     $-34.86
    Liabilities:CreditCard
```

That works fine with `--related`:

```
$ ledger --args-only -f test.ldg reg --related ^Assets:Checking
23-Jan-01 Payment                    Liabilities:CreditCard                  $34.86          $34.86
```

I think this transaction is identical, but doesn't work:

```
bucket Liabilities:CreditCard

2023/01/01 * Payment
    Assets:Checking     $-34.86
```
```
$ ledger --args-only -f test.ldg reg --related ^Assets:Checking
```

I was using `bucket`, and noticed some reports seemed wrong.

**Comment by taviso** [comment]
The problem is that `related_posts::flush()` explicitly checks for posts with the `ITEM_GENERATED`  flag and ignores them.

That comes from `xact_base_t::finalize()`:

https://github.com/ledger/ledger/blob/4f40c3056a68151f52422d54572fa72c0f19151d/src/xact.cc#L213

So the question is, are bucket posts *really* generated? I mean, I understand they're synthetic, but in the same way that the other generated posts are.

 I just applied this patch:

```diff
diff --git a/src/xact.cc b/src/xact.cc
index 961ff010..c0b5d733 100644
--- a/src/xact.cc
+++ b/src/xact.cc
@@ -210,7 +210,7 @@ bool xact_base_t::finalize()
   // been set.
 
   if (journal && journal->bucket && posts.size() == 1 && ! balance.is_null()) {
-    null_post = new post_t(journal->bucket, ITEM_GENERATED);
+    null_post = new post_t(journal->bucket);
     null_post->_state = (*posts.begin())->_state;
     add_post(null_post);
   }

```

That seems to fix the problem and the tests pass, but is it the real solution? I'm tempted to think it is correct, browsing through all the locations that flag is tested, I *think* you would still want them to apply to buckets?

```
100% tests passed, 0 tests failed out of 411
```

**Comment by tbm** [comment]
@jwiegley any input on the analysis from @taviso?

**Comment by taviso** [comment]
Here is my argument that this change should be committed 😄 

It is self-evident that this cannot possibly break anything *unless* you're using `bucket`, which we know for sure is already not working. This change does fix the known issues with bucket, so is clearly an improvement!

If I turn this into a PR with some tests, would you be willing to merge?

**Comment by taviso** [comment]
friendly ping!  I'm wondering if maybe `bucket` is deprecated?

**Comment by afh** [comment]
I do see sense in your reasoning, @taviso. Given my focus is currently in other parts of Ledger I very much would like to rely on @jwiegley expertise opinion on this.

**Comment by jwiegley** [comment]
Hi @taviso, the definition of `ITEM_GENERATED` is fairly clear as to intent:
```
#define ITEM_GENERATED         0x01 // posting was not found in a journal
```
What I think we should do is add another flag, `ITEM_INFERRED`, set this for bucketed items, and then I'm OK with not setting `ITEM_GENERATED`, so long as we have a way to distinguish "items the user actually typed in" from those that Ledger inferred or generated.

**Comment by taviso** [comment]
Okay - sounds good to me, thanks @jwiegley! I've created a PR with that, see #2245.
