### ISSUE TITLE
Assertion fails when total character total size of the transaction is larger than 8192 characters

### ISSUE THREAD

**Issue by dreyder** [ledger/ledger#2244]
I have a split transaction with 825 entries, each includes a metadata text.

Command ```ledger print --no-pager --raw --sort date```  causes exception:
~~~
Error: Assertion failed in "/build/ledger-SR1_DQ/ledger-3.1.3/src/error.cc", line 91:ledger::string ledger::source_context(const path&, std::basic_istream<char>::pos_type, std::basic_istream<char>::pos_type, const string&): len < 8192
~~~

When I shortened the transaction by a few lines (net 0), the execution succeeds.

**Comment by afh** [comment]
Glancing over ledger's code there are a few buffers of 8192, yet I'm at the moment uncertain whether that (should) limit(s) whole transactions.

To better understand your report and investigate—if you are comfortable sharing—could you please provide the output of the following command: `ledger print --no-pager --anon --sort date`

**Comment by dreyder** [comment]
```ledger print --no-pager --anon --sort date``` does not cause error, because it excludes ```--raw```. Without ```--raw``` the metadata in comments is not included in the transaction text and makes the string container smaller than 8192. The issue is the assert of the string size < 8192, which is surprising. This is not an embedded software to be run on a system with very limited resource. Hence, strings should be allowed to grow larger than 8192. Otherwise, documentation must state that a raw journal record can be no larger than 8191 characters.

**Comment by tbm** [comment]
This is the same as #1215

Note that the limit was changed to 65536 in:

commit d31e41659fefc04cf82f0d1cea5dd7f68f4f9664
Author: John Wiegley <johnw@newartisans.com>
Date:   Sun Apr 26 19:06:03 2020 -0700

    Increase the error display text limit

But I don't know why ledger has such an artificial limit.

**Comment by tbm** [comment]
A test case is trivial to make:

./ledger -f 2244.ledger print --raw
Error: Assertion failed in "/home/tbm/tmp/src/ledger/src/error.cc", line 95:ledger::string ledger::source_context(const path&, std::basic_istream<char>::pos_type, std::basic_istream<char>::pos_type, const string&): len < 65536

**Comment by tbm** [comment]
[2244.zip](https://github.com/ledger/ledger/files/11278816/2244.zip)
