### ISSUE TITLE
Strange behavior with multiple currencies, prices db, and dates

### ISSUE THREAD

**Issue by valankar** [ledger/ledger#2252]
I'm noticing a strange behavior with my ledger file and I can't quite figure out what the issue is. I have the following files:

ledger.ledger
```
2018/08/02 Foo
    Assets:Investments:Precious Metals            80.376895222 GOLD @@ $4070.37
    Equity:Opening Balances

2023/04/28 Foo
    Assets:Investments:Precious Metals             -3.21507466 GOLD @@ $6171.25
    Assets:Bank                                        8255.16 SGD @@ $6171.25
```

prices.db
```
P 2023/04/29 GOLD $1999.4
P 2023/04/29 SGD $0.7496589
```

This gives me the following balance:

```
ledger -f ledger.ledger --price-db prices.db -V bal

             $160466  Assets
               $6189    Bank
             $154277    Investments:Precious Metals
              $-4070  Equity:Opening Balances
--------------------
             $156396
```

Now when I change the 2nd entry's date to be 2023/04/29 (today) instead of 2023/04/28, I get the following:

```
ledger -f ledger.ledger --price-db prices.db -V bal

             $154281  Assets
               $6171    Bank
             $148110    Investments:Precious Metals
              $-4070  Equity:Opening Balances
--------------------
             $150211
```

This drop in total doesn't make much sense to me just with the date change. Any ideas?

I'm keeping the current day price in the prices.db file. Once 2023/04/29 is removed from the prices.db and I add 2023/04/30 for the next day, the total corrects itself. But I don't get why it is wrong on the current day.

I'm using `Ledger 3.3.2-20230330`. Thanks.

**Comment by tbm** [comment]
Ledger allows only one price per day.  So when you change the day, you create more pricedb entries: one from the transaction and one from the pricedb entry.  These are different and explain exactly the numbers you're seeing:

```
ledger -f d prices
2018-08-02 GOLD     $50.6410453993985202
2023-04-28 GOLD     $1919.4733101470184832
2023-04-29 GOLD          $1999.4
2023-04-28 SGD      $0.7475627365
2023-04-29 SGD        $0.7496589
```

and:

```
>>> 8255.16*0.7496589 + 77.161820562*1999.4
160465.89819658682
>>> 8255.16*0.7475627365 + 77.161820562*1919.4733101470184832
154281.30513095777
```

**Comment by valankar** [comment]
I see, thanks!
