### ISSUE TITLE
Error in manual query example

### ISSUE THREAD

**Issue by valankar** [ledger/ledger#2254]
Under https://ledger-cli.org/doc/ledger3.html#Controlling-the-Accounts-and-Payees there is an example:

`$ ledger balance --limit 'account=~/Fuel/' and 'payee=~/Chev/'`

Is this actually correct? I think it should be:

`$ ledger balance --limit 'account=~/Fuel/ and payee=~/Chev/'`

**Comment by tbm** [comment]
Thanks, the example is wrong!
