### ISSUE TITLE
trading between commodities in automatic transaction does not balance

### ISSUE THREAD

**Issue by dbear496** [ledger/ledger#2268]
When an automatic transaction deals with trading between commodities -- even with an explicit price -- the transaction will not balance. For example, the following does not balance when the automatic transaction is applied even though 100 apples at $0.20 per apple is clearly $20.

```
= expr 'tag("thetag") == "foo"'
  Assets:My Larder           100 apples        @ $0.200000
  Assets:Checking           $-20

2010/05/31 Farmer's Market
  Assets:My Larder           100 apples        @ $0.200000
  Assets:My Larder           100 pineapples    @ $0.33
  Assets:My Larder           100 "crab apples" @ $0.04
  Assets:Checking
    ; thetag: foo
```

**Comment by tdenny** [comment]
Seeing the same issue. Scares me off of using the commodities feature. I suppose I will just do the math myself and use sub accounts.

```
2010/05/31 Farmer's Market
    Assets:My Larder:Apples        $  20
    Assets:My Larder:Pineapples    $  33
    Assets:My Larder:Crab Apples   $   4
    Assets:Checking                $ -57
```

**Comment by dbear496** [comment]
@tdenny What issue are you seeing exactly? From your example, it doesn't look like you are using automated transactions or multiple commodities.

**Comment by tdenny** [comment]
> @tdenny What issue are you seeing exactly? From your example, it doesn't look like you are using automated transactions.

My fault. I think I misunderstood your OP.

I'm seeing the error `transaction does not balance` when I used commodities in an explicit transaction. I'm fairly certain my problems are a result of trying to use floating point values on my commodities. eg. `3.77 "ground beef" @ $ 3.07`.

Apologies for the noise.

**Comment by dbear496** [comment]
@tdenny  
> I'm seeing the error `transaction does not balance` when I used commodities in an explicit transaction. I'm fairly certain my problems are a result of trying to use floating point values on my commodities. eg. `3.77 "ground beef" @ $ 3.07`.

I recommend you put this directive at the top of your journal:
```
commodity $
  format $0,000.00
  alias USD
```
If you do this, then transactions will only have to balance to the nearest cent. For example:
```
2023-07-18 *
  freezer       3.77 "ground beef" @ $ 3.07
  bank account  $-11.57
```
Ledger shouldn't complain about the unbalanced $0.0039 because the format directive specifies only two decimal places. If you still have problems where there is an unbalanced penny or two, then I would recommend any of 1) adding an _adjustements_ posting with a blank amount to soak up the residual pennies, 2) omitting the explicit $-11.57 and let ledger calculate that automatically, or 3) omitting the explicit $3.07. If you still have issues, then it's probably from a syntax mistake like a wrong whitespace.
