### ISSUE TITLE
multiple commodities causes error: There cannot be null amounts after balancing a transaction

### ISSUE THREAD

**Issue by dbear496** [ledger/ledger#2270]
I have a journal like so:
```
commodity USD
  format 0.00 USD ; error
  ;format 0.000 USD ; no error

2023-04-01
  acc0  0.123 BTC @ 30508.00 USD
  acc1  -3752.48 USD
  fee  0.0002 BTC
  acc0  -0.0002 BTC
  adjustments
```
I expect ledger to figure out that the adjustments account should be deducted 0.004 USD, but instead I get:
```
While parsing file "tmp.dat", line 10:
Error: There cannot be null amounts after balancing a transaction
```
The error message goes away if I change the precision of USD to three decimal places. This does not make sense to me since ledger is supposed to internally use infinite-precision rational values.

And anyway, it would be nice if ledger could resolve a null value to zero instead of giving an error. I don't always want to have to figure out whether it will be zero to know whether I need to add an adjustments posting. I want to just add an adjustments posting whenever it may be necessary, and if it isn't used then great.

**Comment by tbm** [comment]
This works fine:

```
2023-07-01
    A    1.00 EUR
    B   -1.00 EUR
    Adjustments
```

So if `Adjustments` can be empty here, I don't see why it shouldn't be allowed in your example.  I wonder if it's because there are two commodities (BTC, USD), but the 0.0002 BTC balances out, so it shouldn't matter.

Oh, yes, indeed, this also fails:

```
2023-07-01
    A    1.00 EUR
    B   -1.00 EUR
    C    1.00 GBP
    D   -1.00 GBP
    Adjustments
```

gives:

```
Error: There cannot be null amounts after balancing a transaction
```

**Comment by dbear496** [comment]
I suppose rounding isn't really part of the issue then.

**Comment by dbear496** [comment]
I submitted a PR that fixes this issue and adds a regress test.
