### ISSUE TITLE
The note query syntax might be broken

### ISSUE THREAD

**Issue by taviso** [ledger/ledger#2275]
I don't know if I'm doing something wrong, but the docs say that you can query notes with `=regex`.

>     note regex (=regex)
>                   Query on anything found in an item's note.

The other query characters seem to work:

```
$ ledger reg @Target # works
$ ledger reg %travel # works
```

However, this just dumps my whole ledger: `ledger reg =NoNoteShouldMatch`

(The syntax `reg note foo` *does* work, so there is a workaround)

**Comment by saneef** [comment]
I also face the same problem with v3.3.2-20230330.

**Comment by taviso** [comment]
Any chance we can get #2290 merged? :smiley:  @jwiegley

**Comment by jwiegley** [comment]
>>>>> "TO" == Tavis Ormandy ***@***.***> writes:

TO> Any chance we can get #2290 merged? 😃 @jwiegley

Merged!

-- 
John Wiegley                  GPG fingerprint = 4710 CF98 AF9B 327B B80F
http://newartisans.com                          60E1 46C4 BD1A 7AC1 4BA2
