### ISSUE TITLE
Tests relating to python support should be avoided if ledger is built without python support

### ISSUE THREAD

**Issue by Earnestly** [ledger/ledger#2324]
* ledger https://github.com/ledger/ledger/commit/6372a7bfebff58ca438d690f7a17608e01126aa5

I build ledger with `-D USE_PYTHON=OFF` but the python specific tests are still executed during `make check` resulting in several test failures:

```
The following tests FAILED:
         47 - BaselineTest_dir-import_py (Failed)
         49 - BaselineTest_dir-python_py (Failed)
         59 - BaselineTest_feat-import_py (Failed)
         60 - BaselineTest_feat-option_py (Failed)
         62 - BaselineTest_feat-value_py (Failed)
        311 - RegressTest_4D9288AE_py (Failed)
        349 - RegressTest_78AB4B87_py (Failed)
        362 - RegressTest_9188F587_py (Failed)
        379 - RegressTest_B21BF389_py (Failed)
        423 - RegressTest_xact_code_py (Failed)
```

Should these tests either not be run or set to be expected failure?

**Comment by afh** [comment]
Thanks for raising this, @Earnestly, I think these tests should be omitted when Ledger is built without Python support. I'll look into preparing an appropriate PR and will cc you on it if you don't mind…

**Comment by afh** [comment]
#2325 is now up for review, @Earnestly, would you be willing to test the proposed changes in the PR and see if they fix this issue for you too?

**Comment by Earnestly** [comment]
Applied #2325 locally and it appears to be working:

```
100% tests passed, 0 tests failed out of 413
```
