### ISSUE TITLE
acprep dependency install error on Ubuntu 22.04

### ISSUE THREAD

**Issue by tmartin-gh** [ledger/ledger#2346]
https://github.com/ledger/ledger/blob/f8624f59419090aa59ab2f75626a7b1102558dfd/acprep#L545

Should be `python3-dev`.

Attempting to install `python-dev` results in error message:
```
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-dev python2 python-dev-is-python3
```

Might also be a good idea to add support for `noble` (Ubuntu 24.04) since it's out now.  I can create a PR if there's interest.

**Comment by afh** [comment]
Thank you for raising this issue @tmartin-gh, could I interest you in creating PRs for the two issues you mentioned?
