### ISSUE TITLE
Stock sale transactions using the implicit commodity do not balance, they are balanced only when using an explicit commodity

### ISSUE THREAD

**Issue by hoylen** [ledger/ledger#2353]
Stock sale transactions are balanced when explicit commodities are used to represent prices, but do not balance when the implicit commodity is used.

This is the example from [section 4.5.2 Buying and Selling Stock](https://ledger-cli.org/doc/ledger3.html#Buying-and-Selling-Stock) of the manual.

Values are represented using explicit commodities. The explicit commodity is `$`, with  the _lot price_ being `$30.00` and the _sale price_ of `$50.00`.

```
2005-08-01 Stock sale
    Assets:Broker                                -50 AAPL {$30.00} @ $50.00
    Expenses:Broker:Commissions               $19.95
    Income:Capital Gains                  $-1,000.00
    Assets:Broker                          $2,480.05
```

But the same transaction is incorrectly treated as not balanced, when values are represented using the implicit commodity.  When the _lot price_ is `30.00` and _sale price_ is `50.00`.

## Expected behaviour

The following transaction should be balanced.

```
2005-08-01 Stock sale
    Assets:Broker                                -50 AAPL {30.00} @ 50.00
    Expenses:Broker:Commissions                19.95
    Income:Capital Gains                   -1,000.00
    Assets:Broker                           2,480.05
```

## Actual behaviour

Ledger 3.3.2-20230330 says the transaction is not	balanced.

```
While parsing file "commodity-bug.ledger", line 10:
While balancing transaction from "commodity-bug.ledger", lines 6-10:
> 2005-08-01 Stock sale
>     Assets:Broker                                -50 AAPL {30.00} @ 50.00
>     Expenses:Broker:Commissions                19.95
>     Income:Capital Gains                   -1,000.00
>     Assets:Broker                           2,480.05
Unbalanced remainder is:
               -1000
Amount to balance against:
                2500
Error: Transaction does not balance
```

It appears to be incorrectly using the _sale price_ as the _lot price_. Because the transaction would be balanced if using either:

- `-50 AAPL @ 30.00` or
- `-50 AAPL {30.00} @ 30.00`

But, of course, those are not the correct way to represent the sale posting. They do not correspond with how the posting is represented when explicit commodities are used, which is: _amount_ _stock_ `{` _lot price_ `}` `@` _sale price_.

**Comment by tbm** [comment]
There is no "implicit commodity".  You're using an amount without commodity.  This isn't a good idea and will lead to problems.  Add a commodity.  That's the real solution.
