### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by jwiegley** [ledger/ledger#510]
This issue is for tracking discussion of supporting Python 3 in the Ledger Python API.

**Comment by jwiegley** [comment]
@afh Do you know how close we were on this at the Ledger hackathon?

**Comment by afh** [comment]
Hi @jwiegley, it's been way too long 👋 😃 

We were really close to having Ledger Python3 support. I've rebased my work-in-progress branch [afh/ledger@wip/python3](https://github.com/afh/ledger/tree/wip/python3) onto next.

The current state is that the ledger python module works with Python 3, but the following tests fail:

```
BaselineTest_feat-option_py
BaselineTest_feat-value_py
BaselineTest_opt-lots
RegressTest_4D9288AE_py
RegressTest_78AB4B87_py
RegressTest_9188F587_py
RegressTest_B21BF389_py
RegressTest_xact_code_py
```

There are more issues I uncovered, e.g. calling `close_journal_files()` from python randomly crashing…

I've started to re-activate my ledger development setup and will share more details about the current state of things, once I have it working again.

Is it possible for you to build ledger with Python3 support from [afh/ledger@wip/python3](https://github.com/afh/ledger/tree/wip/python3)?
And are the same tests failing for you?

**Comment by pmiddend** [comment]
Any update on this?

**Comment by andreas-h** [comment]
@afh @jwiegley I'd be happy to help, but obviously want to avoid duplicating efforts.  Can I just start with the "next" branch, or which branch should I build upon?

**Comment by tbm** [comment]
@andreas-h isn't @afh's code in https://github.com/afh/ledger/tree/wip/python3 as he mentioned a few posts above? I'd *assume* this is what you should use.

**Comment by andreas-h** [comment]
> @andreas-h isn't @afh's code in https://github.com/afh/ledger/tree/wip/python3 as he mentioned a few posts above? I'd _assume_ this is what you should use.

Yes, of course you're right, there's @afh's wip/python3 branch which I forgot to explicitly mention.  But it'd be nice to have their "go" since I don't like investing my time based on assumptions ;)

**Comment by scfc** [comment]
I have rebased @afh's branch onto `next` at https://github.com/scfc/ledger/tree/afh/wip/python3.  It does not compile (but has a number of interesting commits for the build system which I will post pull requests for), and I believe the logic is currently flawed as it seems to (try to) compile Ledger for the system's "standard" Python.  Instead, this should be independent: You should be able to compile support for Python 2 if your system's default is Python 3, vice versa and ideally for both versions (if possible).

**Comment by scfc** [comment]
I stand corrected: While IMHO the `python:` section in `.travis.yml` is still flawed, the idea to have to select one Python version per build seems to be sensible looking at https://src.fedoraproject.org/rpms/csdiff/blob/1c988d4b90ee0a2db409b8459ad93e97dfe1a253/f/csdiff.spec#_70 where CMake is called in separate directories with `-DPYTHON_EXECUTABLE` set to different values.

**Comment by aparkerlue** [comment]
Is there a pull request that one could contribute to?

**Comment by bremner** [comment]
FYI I've been asked to drop the python2 module from Debian as part of the removal of python2 from Debian testing/unstable. I can probably wait a bit, but not indefinitely.
