### ISSUE TITLE
Error parsing investment purchases

### ISSUE THREAD

**Issue by MisterY** [ledger/ledger#530]
I have a ledger file that contains fund purchases, exported from GnuCash. The records are exported as:
```
2013/09/03 * Buy EXI5
	Assets:Investments:Brokerage:EXI5        2.00 EXI5 @@ 25.96 EUR
	Trading:CURRENCY:EUR                    25.96 EUR
	Assets:Bank Accounts:Checking          -25.96 EUR
	Trading:XETRA:EXI5                      -2.00 EXI5 @@ 25.96 EUR
```
When running Ledger on this file, I'm getting **Error: Unexpected char '5' (Note: inline math requires parentheses)** errors at the first line with EXI5 symbol ("2.00 EXI5 @@ 25.96 EUR").
The same happens for all securities that contain digits in their symbols (EXI5, EL49, EL4X, etc.).

Could you please point out the reason/source for the error so that I can make appropriate adjustments and/or submit bug reports where they are due.
I'm using PieCash to export my GnuCash book into ledger format.
Thanks!

**Comment by peterkeen** [comment]
Commodities with numbers or symbols in them need to be wrapped in double
quotes.

**Comment by MisterY** [comment]
Thanks! I've just submitted a bug report for PieCash. Is it safe to wrap all symbols into double quotes?

**Comment by peterkeen** [comment]
I'm not sure. I know that postfix symbols like `-100 "EUR"` are safe, but
I'm not sure what ledger does with something like `"$"-100.00`.

**Comment by MisterY** [comment]
No worries. Will try it both ways and submit a patch.
Wrapping all symbols by default would just be easier for writing and lighter or the processing time, I guess.
Thank you!
