### ISSUE TITLE
Tests failing on Alpine (x86_64 and ppc64le)

### ISSUE THREAD

**Issue by rgdoliveira** [ledger/ledger#550]
I'm trying to package ledger on Alpine (see PR https://github.com/alpinelinux/aports/pull/3626) and some tests are failing when running `make check`.

* x86_64 arch :
The following tests FAILED:
27 - BaselineTest_cmd-org (Failed)
29 - BaselineTest_cmd-pricedb (Failed)
31 - BaselineTest_cmd-prices (Failed)
283 - RegressTest_786A3DD0 (Failed)

* ppc64le arch:
The following tests FAILED:
	142 - BaselineTest_opt-lots (Failed)
	227 - RegressTest_1057 (Failed)

**Comment by arunisaac** [comment]
On GuixSD, `BaselineTest_cmd-org` alone fails. I only ran `make check` (a single job). I did not use `make check -jN` (multiple jobs in parallel). The error message is as follows.

```
FAILURE in output from /tmp/ledger/test/baseline/cmd-org.test:
--
$ledger -f "/tmp/ledger/test/baseline/cmd-org.test" org
--
  @@ -5,8 +5,6 @@
   |||Test 3|*|D|-20.00 EUR|0.00 EUR| Payee: Test 3
   |12-Mar-25|99|Test 4|*|E|30.00 GBP|30.00 GBP|
   ||||*|F|-30.00 GBP|0.00 GBP|
  -|12-Mar-26|test|Test 5|*|G|1 AAA|0.00 GBP|
  -|||||||1 AAA|
  -||||*|H|$-10|0.00 GBP|
  +|12-Mar-26|test|Test 5|*|G|1 AAA|1 AAA|
  +||||*|H|$-10|1 AAA|
   |||||||$-10|
  -|||||||1 AAA|
E[cmd-org.test]STDERR:
```

**Comment by afh** [comment]
Closing as outdated, if the issue still exists, please re-open this issue providing updated context.
