### ISSUE TITLE
Payee metadata tag ignored by --check-payees

### ISSUE THREAD

**Issue by sephelps** [ledger/ledger#556]
```
account Exp
account Ass
payee Test Payee
tag Payee

2018-01-01 * Test Payee
	Exp		$20
	Exp		$20 ; Payee: Another Payee
	Ass		
```
`ledger -f ledger.dat bal --pedantic --explicit --check-payees`

Shouldn't `--check-payees` cause an error for 'Another Payee?'

**Comment by tbm** [comment]
Confirmed.

**Comment by felipelalli** [comment]
Maybe the doc should be updated?

https://www.ledger-cli.org/3.0/doc/ledger3.html#Command-Directives

`The payee name used with the tag is not enforced by the --check-payees option, due to a bug: https://github.com/ledger/ledger/issues/556. `

**Comment by tbm** [comment]
@felipelalli commit fc8e4ced042a4e6b154d7b6e0159d0f92f updated the docs, but we have to make a new ledger release before the docs on the website are updated.
