### ISSUE TITLE
Strange date output from ledger xact on macOS

### ISSUE THREAD

**Issue by bcc32** [ledger/ledger#565]
When using the xact command to copy a past transaction, I get very strange output in place of the date:

```
 ❯ ledger -f ledger.ldg xact sub
00000000: ba5c 0201 2053 7562 7761 790a 2020 2020  .\.. Subway.
00000010: 4578 7065 6e73 6573 3a46 6f6f 6420 2020  Expenses:Food
00000020: 2020 2020 2020 2020 2020 2020 2020 2020
00000030: 2020 2020 2020 2020 352e 3030 2055 5344          5.00 USD
00000040: 0a20 2020 2041 7373 6574 733a 4361 7368  .    Assets:Cash
00000050: 0a                                       .
```

The first four bytes seem to be some kind of binary data, and they change each time I run the same command.  This bug does not appear to occur in the Linux version.

**Comment by tbm** [comment]
Same as #544 and #546

**Comment by tbm** [comment]
I'm closing this as a duplicate of issue #546 which was fixed a few days ago.  If your issue is still there, please let me know and we can re-open this issue.

**Comment by bcc32** [comment]
Looks like the master branch works fine on my machine now.  Thanks for your help.
