### ISSUE TITLE
Ability to write self-contained python programs using ledger

### ISSUE THREAD

**Issue by pmiddend** [ledger/ledger#569]
Hi! I wrote a small program that uses ledger's Python API. It works, but only if I start it via `ledger python my_program.py` (via `./my_program.py`, it just outputs `No module named ledger` in `import ledger`). Is there currently a way to write programs I can package and start independent of the ledger executable? Or is there something in my setup that's causing the issues? I'm using NixOS, by the way.

**Comment by afh** [comment]
Hi @pmiddend,
                                                      
yes, there is a way: set the `PYTHONPATH` environment variable (see [`python (1)`](https://www.manpagez.com/man/1/python/)) to the directory containing the `ledger.so` python module.

**Comment by pmiddend** [comment]
Ah, I see, thanks!
