### ISSUE TITLE
--init-file is ignored (BZ#695)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#695]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#695
From: John Wiegley (@jwiegley)

**Comment by andrew521** [comment]
$ ledger --version
Ledger 3.1.3-20190331, the command-line accounting tool

issue not fixed. whenever ~/.ledgerrc is present, the init file specified is ignored and the default one is loaded.
