### ISSUE TITLE
Error: Divide by zero for 1/9 (BZ#777)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#777]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#777
From: Martin Michlmayr (@tbm)

**Comment by tbm** [comment]
same as #1086

**Comment by tbm** [comment]
This was fixed in:

commit 49cf3323ae2079b7ce1be101dc43780ce8e4296e
Author: John Wiegley <johnw@newartisans.com>
Date:   Thu Mar 23 11:23:39 2023 -0700

    Change a use of is_realzero to just is_zero
    
    This is needed to avoid a possible divide by zero.

**Comment by afh** [comment]
Thanks for closing out the issues related to 49cf3323ae2079b7ce1be101dc43780ce8e4296e, @tbm, very much appreciated 🙏
