### ISSUE TITLE
Assertion failed with unbalanced remainder and input from stdin (BZ#788)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#788]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#788
From: Martin Michlmayr (@tbm)
CC:   unknown user, @thdox

**Comment by MEschenbacher** [comment]
I just triggered the error on version 3.2.1-20200518:

```
$ ledger -f <(cat journal) print
Error: boost::filesystem::file_size: Operation not permitted: "/proc/self/fd/11"
```
