### ISSUE TITLE
automated transactions happen after balance assertion logic (BZ#983)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#983]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#983
From: Stijn Debrouwere (@debrouwere)
CC:   unknown user

**Comment by 501st-alpha1** [comment]
I think this was the same bug as #1127, which was fixed by #1649, so this issue can be closed.

**Comment by tbm** [comment]
Ok, I'm closing this then as per comment from @501st-alpha1. Thanks

@debrouwere if this isn't fixed, please shout.
